import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.95.0";
const origins=new Set(["https://dolphin-abi-pool.gerayeli60.chatgpt.site","https://dolphin-abi.vercel.app","http://localhost:3000","http://localhost:3001"]),roles=new Set(["owner","branch_manager","receptionist"]);
function cors(req:Request){const o=req.headers.get("origin")??"";return{"Access-Control-Allow-Origin":origins.has(o)?o:"https://dolphin-abi.vercel.app","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, OPTIONS","Content-Type":"application/json","Cache-Control":"no-store","Vary":"Origin"}}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors(req)})}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});const origin=req.headers.get("origin")??"";if(origin&&!origins.has(origin))return json(req,{error:"Forbidden"},403);
 const admin=createClient(Deno.env.get("SUPABASE_URL")??"",Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",{auth:{persistSession:false,autoRefreshToken:false}}),token=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"")??"";const {data:auth,error:authError}=await admin.auth.getUser(token);if(authError||!auth.user)return json(req,{error:"Unauthorized"},401);
 const {data:access}=await admin.from("organization_users").select("organization_id,role,branch_id,status").eq("user_id",auth.user.id).eq("status","active").maybeSingle();if(!access||!roles.has(access.role))return json(req,{error:"Staff access required"},403);const org=access.organization_id,scope=access.role==="owner"?null:access.branch_id;if(access.role!=="owner"&&!scope)return json(req,{error:"Branch access required"},403);{const {data:plat}=await admin.from("profiles").select("is_platform_admin").eq("id",auth.user.id).maybeSingle();if(!plat?.is_platform_admin){const {data:orgRow}=await admin.from("organizations").select("status,subscription_ends_on").eq("id",org).maybeSingle();const todayStr=new Date().toISOString().slice(0,10);if(!orgRow||orgRow.status!=="active"||(orgRow.subscription_ends_on&&orgRow.subscription_ends_on<todayStr))return json(req,{error:"Subscription suspended"},403)}}
 if(req.method!=="GET")return json(req,{error:"Method not allowed"},405);
 const tz="Asia/Tehran",today=new Intl.DateTimeFormat("en-CA",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
 const tehranOffset=()=>{const now=new Date(),utc=new Date(now.toLocaleString("en-US",{timeZone:"UTC"})),local=new Date(now.toLocaleString("en-US",{timeZone:tz}));return (local.getTime()-utc.getTime())/3600000};
 const startOfToday=new Date(new Date(today+"T00:00:00Z").getTime()-tehranOffset()*3600000).toISOString();
 const sevenDaysAgo=new Date(new Date(startOfToday).getTime()-7*86400000).toISOString();
 let memberQ=admin.from("members").select("id,status").eq("organization_id",org),paymentQ=admin.from("payment_records").select("id,amount,method,status,paid_at,branch_id,member_id").eq("organization_id",org).eq("status","paid").gte("paid_at",sevenDaysAgo),visitQ=admin.from("attendance_events").select("id,branch_id,member_id,event_type,occurred_at").eq("organization_id",org).eq("event_type","entry").gte("occurred_at",startOfToday),sessionQ=admin.from("pool_sessions").select("id,branch_id,title,starts_at,ends_at,capacity,audience,status").eq("organization_id",org).gte("ends_at",startOfToday).lte("starts_at",new Date(new Date(startOfToday).getTime()+36*3600000).toISOString()).order("starts_at"),auditQ=admin.from("audit_logs").select("id,action,entity_type,details,created_at,actor_user_id").eq("organization_id",org).order("created_at",{ascending:false}).limit(12),insideQ=admin.from("attendance_events").select("id,branch_id,member_id").eq("organization_id",org).eq("event_type","entry").order("occurred_at",{ascending:false}).limit(1000);
 if(scope){memberQ=memberQ.eq("home_branch_id",scope);paymentQ=paymentQ.eq("branch_id",scope);visitQ=visitQ.eq("branch_id",scope);sessionQ=sessionQ.eq("branch_id",scope);insideQ=insideQ.eq("branch_id",scope)}
 const [{data:members,error:me},{data:payments,error:pe},{data:visits,error:ve},{data:sessions,error:se},{data:audit,error:ae},{data:insideEvents,error:ie}]=await Promise.all([memberQ,paymentQ,visitQ,sessionQ,auditQ,insideQ]);
 if(me||pe||ve||se||ae||ie)return json(req,{error:"Unable to load dashboard"},500);
 const activeMembers=(members??[]).filter(x=>x.status==="active").length,todayPayments=(payments??[]).filter(x=>x.paid_at>=startOfToday),todayRevenue=todayPayments.reduce((s,x)=>s+Number(x.amount),0),todayVisits=(visits??[]).length;
 const inside=new Set<string>();for(const e of insideEvents??[])if(!inside.has(e.member_id))inside.add(e.member_id);
 const sessionIds=new Set((sessions??[]).map(x=>x.id)),{data:reservations}=sessionIds.size?await admin.from("session_reservations").select("session_id,status").eq("organization_id",org).in("session_id",[...sessionIds]):{data:[]};
 const reserved=new Map<string,number>();for(const r of reservations??[])if(r.status==="confirmed")reserved.set(r.session_id,(reserved.get(r.session_id)??0)+1);
 const memberIds=[...new Set([...todayPayments,...visits??[]].map(x=>x.member_id).filter(Boolean))] as string[],{data:memberNames}=memberIds.length?await admin.from("members").select("id,full_name").in("id",memberIds):{data:[]},nameMap=new Map((memberNames??[]).map(x=>[x.id,x.full_name]));
 const activity=(audit??[]).map(x=>({id:x.id,action:x.action,entity_type:x.entity_type,details:x.details,created_at:x.created_at,actor:auth.user.id===x.actor_user_id?"شما":x.actor_user_id?"کاربر سیستم":"سیستم"}));
 return json(req,{access:{role:access.role,branch_id:access.branch_id},stats:{activeMembers,todayRevenue,todayRevenueCount:todayPayments.length,todayVisits,currentlyInside:inside.size,todaySessions:(sessions??[]).length},sessions:sessions??[],reservations:Object.fromEntries(reserved),revenue7d:(()=>{const days:string[]=[];const now=new Date(new Date(startOfToday).getTime());for(let i=6;i>=0;i--){days.push(new Date(now.getTime()-i*86400000).toISOString().slice(0,10))}return days.map(d=>({day:d,amount:(payments??[]).filter(x=>new Intl.DateTimeFormat("en-CA",{timeZone:tz,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(x.paid_at))===d).reduce((s,x)=>s+Number(x.amount),0)}))})(),recentPayments:todayPayments.slice(0,5).map(x=>({id:x.id,amount:x.amount,method:x.method,paid_at:x.paid_at,member:x.member_id?nameMap.get(x.member_id)??"عضو":"—"})),activity});
});
