"use client";
import {ArrowRight,Building2,Check,CircleOff,Edit3,Loader2,MapPin,Phone,Plus,RefreshCw,ShieldCheck,Trash2,Users,Waves,X} from "lucide-react";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {functionsUrl,supabase} from "../../lib/supabase-browser";

type Manager={id:string;full_name:string;username:string;branch_id:string|null};
type Branch={id:string;name:string;code:string;phone:string|null;address:string|null;capacity:number;status:"active"|"inactive";user_count:number;member_count:number;active_member_count:number;session_count:number;managers:Manager[]};
const errorLabels:Record<string,string>={"Branch code already exists":"کد شعبه قبلاً استفاده شده است.","Move or deactivate active branch users first":"ابتدا کاربران فعال این شعبه را منتقل یا غیرفعال کنید.","Branch has related records and cannot be deleted":"این شعبه دارای سابقه است و امکان حذف آن وجود ندارد.","Owner access required":"فقط مدیر کل به این بخش دسترسی دارد."};
async function api(path="",init?:RequestInit){const {data}=await supabase.auth.getSession();const response=await fetch(functionsUrl+"/admin-branches"+path,{...init,headers:{Authorization:`Bearer ${data.session?.access_token??""}`,"Content-Type":"application/json",...(init?.headers??{})}});const result=await response.json();if(!response.ok)throw new Error(errorLabels[result.error]??result.error??"خطا در ارتباط با سرور");return result}

export default function BranchesPage(){
 const [branches,setBranches]=useState<Branch[]>([]),[managers,setManagers]=useState<Manager[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[editing,setEditing]=useState<Branch|null|undefined>(undefined),[toast,setToast]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const r=await api();setBranches(r.branches);setManagers(r.eligible_managers)}catch(e){setToast(e instanceof Error?e.message:"خطا در دریافت شعب")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function action(branchId:string,payload:object){setBusy(branchId);try{await api("",{method:"PATCH",body:JSON.stringify({branch_id:branchId,...payload})});setToast("تغییرات با موفقیت ذخیره شد");await load()}catch(e){setToast(e instanceof Error?e.message:"عملیات ناموفق بود")}finally{setBusy("")}}
 async function remove(branch:Branch){if(!window.confirm(`آیا از حذف شعبه «${branch.name}» مطمئن هستید؟`))return;setBusy(branch.id);try{await api("?branch_id="+encodeURIComponent(branch.id),{method:"DELETE"});setToast("شعبه حذف شد");await load()}catch(e){setToast(e instanceof Error?e.message:"حذف شعبه ممکن نیست")}finally{setBusy("")}}
 return <main className="users-page branches-page" dir="rtl">
  <header className="users-topbar"><a href="/" className="users-back"><ArrowRight/> بازگشت به داشبورد</a><div className="users-brand"><span><Waves/></span><b>دلفین آبی</b></div><div className="users-secure"><ShieldCheck/> مدیریت امن شعب</div></header>
  <section className="users-container">
   <div className="users-heading"><div><small>ساختار مجموعه</small><h1>شعبه‌ها</h1><p>اطلاعات، ظرفیت، مدیر و وضعیت فعالیت شعب را مدیریت کنید.</p></div><button className="users-primary" onClick={()=>setEditing(null)}><Plus/> افزودن شعبه</button></div>
   <section className="users-summary"><div><span className="violet"><Building2/></span><p>کل شعب<b>{branches.length}</b></p></div><div><span className="green"><Check/></span><p>شعب فعال<b>{branches.filter(b=>b.status==="active").length}</b></p></div><div><span className="orange"><Users/></span><p>اعضای فعال<b>{branches.reduce((sum,b)=>sum+b.active_member_count,0)}</b></p></div></section>
   <div className="branch-toolbar"><button onClick={()=>void load()}><RefreshCw className={loading?"spin":""}/> بروزرسانی اطلاعات</button></div>
   {loading?<div className="users-panel users-empty"><Loader2 className="spin"/><p>در حال دریافت شعب...</p></div>:<section className="branch-grid">{branches.map(branch=><article className="branch-card" key={branch.id}>
    <div className="branch-card-head"><span className={branch.status==="active"?"active":"inactive"}><Building2/></span><div><h2>{branch.name}</h2><code dir="ltr">{branch.code}</code></div><em className={branch.status}>{branch.status==="active"?"فعال":"غیرفعال"}</em></div>
    <div className="branch-contact"><p><MapPin/>{branch.address??"آدرس ثبت نشده"}</p><p><Phone/>{branch.phone??"تلفن ثبت نشده"}</p></div>
    <div className="branch-numbers"><span><small>ظرفیت</small><b>{branch.capacity.toLocaleString("fa-IR")}</b></span><span><small>اعضا</small><b>{branch.member_count.toLocaleString("fa-IR")}</b></span><span><small>کاربران</small><b>{branch.user_count.toLocaleString("fa-IR")}</b></span><span><small>سانس‌ها</small><b>{branch.session_count.toLocaleString("fa-IR")}</b></span></div>
    <label className="manager-select">مدیر شعبه<select value={branch.managers[0]?.id??""} disabled={busy===branch.id} onChange={e=>void action(branch.id,{action:"assign_manager",manager_id:e.target.value})}><option value="">بدون مدیر</option>{managers.map(manager=><option value={manager.id} key={manager.id}>{manager.full_name} (@{manager.username})</option>)}</select></label>
    <footer><button onClick={()=>setEditing(branch)}><Edit3/> ویرایش</button><button className={branch.status==="active"?"warn":"activate"} disabled={busy===branch.id} onClick={()=>void action(branch.id,{action:"set_status",status:branch.status==="active"?"inactive":"active"})}>{busy===branch.id?<Loader2 className="spin"/>:branch.status==="active"?<CircleOff/>:<Check/>}{branch.status==="active"?"غیرفعال‌سازی":"فعال‌سازی"}</button><button className="delete" disabled={busy===branch.id} onClick={()=>void remove(branch)} title="حذف شعبه"><Trash2/></button></footer>
   </article>)}</section>}
  </section>
  {editing!==undefined&&<BranchModal branch={editing} onClose={()=>setEditing(undefined)} onSaved={async()=>{setEditing(undefined);setToast("اطلاعات شعبه ذخیره شد");await load()}}/>}
  {toast&&<div className="users-toast"><Check/>{toast}<button onClick={()=>setToast("")}><X/></button></div>}
 </main>
}
function BranchModal({branch,onClose,onSaved}:{branch:Branch|null;onClose:()=>void;onSaved:()=>void}){
 const [saving,setSaving]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget),body={name:f.get("name"),code:f.get("code"),phone:f.get("phone"),address:f.get("address"),capacity:Number(f.get("capacity"))};try{if(branch)await api("",{method:"PATCH",body:JSON.stringify({branch_id:branch.id,action:"update",...body})});else await api("",{method:"POST",body:JSON.stringify(body)});onSaved()}catch(err){setError(err instanceof Error?err.message:"ذخیره شعبه ناموفق بود")}finally{setSaving(false)}}
 return <div className="users-modal-backdrop"><form className="users-modal" onSubmit={submit}><div className="modal-head"><div><span><Building2/></span><div><h2>{branch?"ویرایش شعبه":"افزودن شعبه"}</h2><p>مشخصات اجرایی شعبه را وارد کنید.</p></div></div><button type="button" onClick={onClose}><X/></button></div><div className="modal-grid"><label className="wide">نام شعبه<input name="name" defaultValue={branch?.name} required minLength={2} autoFocus placeholder="مثلاً شعبه مرکزی"/></label><label>کد شعبه<input name="code" defaultValue={branch?.code} required pattern="[a-z0-9][a-z0-9_-]{1,19}" dir="ltr" placeholder="central"/></label><label>ظرفیت مجموعه<input name="capacity" defaultValue={branch?.capacity??0} required type="number" min={0} max={100000}/></label><label>تلفن<input name="phone" defaultValue={branch?.phone??""} dir="ltr" placeholder="021..."/></label><label className="wide">آدرس<input name="address" defaultValue={branch?.address??""} placeholder="آدرس کامل شعبه"/></label></div>{error&&<p className="modal-error">{error}</p>}<footer><button type="button" onClick={onClose}>انصراف</button><button className="users-primary" disabled={saving}>{saving?<Loader2 className="spin"/>:<Check/>} ذخیره شعبه</button></footer></form></div>
}
