import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.95.0";
const origins=new Set(["https://dolphin-abi-pool.gerayeli60.chatgpt.site","https://dolphin-abi.vercel.app","http://localhost:3000","http://localhost:3001"]),roles=new Set(["owner","branch_manager","receptionist"]);
function cors(req:Request){const o=req.headers.get("origin")??"";return{"Access-Control-Allow-Origin":origins.has(o)?o:"https://dolphin-abi.vercel.app","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Content-Type":"application/json","Cache-Control":"no-store","Vary":"Origin"}}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors(req)})}function txt(v:unknown,n:number){return String(v??"").trim().slice(0,n)}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});const origin=req.headers.get("origin")??"";if(origin&&!origins.has(origin))return json(req,{error:"Forbidden"},403);
 const admin=createClient(Deno.env.get("SUPABASE_URL")??"",Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",{auth:{persistSession:false,autoRefreshToken:false}}),token=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"")??"";const {data:auth,error:authError}=await admin.auth.getUser(token);if(authError||!auth.user)return json(req,{error:"Unauthorized"},401);
 const {data:access}=await admin.from("organization_users").select("organization_id,role,branch_id,status").eq("user_id",auth.user.id).eq("status","active").maybeSingle();if(!access||!roles.has(access.role))return json(req,{error:"Staff access required"},403);const org=access.organization_id,scope=access.role==="owner"?null:access.branch_id;if(access.role!=="owner"&&!scope)return json(req,{error:"Branch access required"},403);{const {data:plat}=await admin.from("profiles").select("is_platform_admin").eq("id",auth.user.id).maybeSingle();if(!plat?.is_platform_admin){const {data:orgRow}=await admin.from("organizations").select("status,subscription_ends_on").eq("id",org).maybeSingle();const todayStr=new Date().toISOString().slice(0,10);if(!orgRow||orgRow.status!=="active"||(orgRow.subscription_ends_on&&orgRow.subscription_ends_on<todayStr))return json(req,{error:"Subscription suspended"},403)}}
 if(req.method==="GET"){const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tehran",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());let branchQ=admin.from("branches").select("id,name").eq("organization_id",org).eq("status","active").order("name"),memberQ=admin.from("members").select("id,member_number,full_name,home_branch_id,status").eq("organization_id",org).eq("status","active").order("full_name").limit(500),sessionQ=admin.from("pool_sessions").select("id,branch_id,title,starts_at,ends_at,status").eq("organization_id",org).gte("ends_at",new Date(Date.now()-6*3600000).toISOString()).lte("starts_at",new Date(Date.now()+24*3600000).toISOString()).order("starts_at"),eventQ=admin.from("attendance_events").select("id,branch_id,member_id,session_id,event_type,method,recorded_by,occurred_at").eq("organization_id",org).order("occurred_at",{ascending:false}).limit(500),membershipQ=admin.from("memberships").select("id,member_id,remaining_sessions,ends_on,status").eq("organization_id",org).eq("status","active").lte("starts_on",today).gte("ends_on",today).or("remaining_sessions.is.null,remaining_sessions.gt.0").order("ends_on");if(scope){branchQ=branchQ.eq("id",scope);memberQ=memberQ.eq("home_branch_id",scope);sessionQ=sessionQ.eq("branch_id",scope);eventQ=eventQ.eq("branch_id",scope)}
  const [{data:branches,error:be},{data:members,error:me},{data:sessions,error:se},{data:events,error:ee},{data:memberships,error:mse}]=await Promise.all([branchQ,memberQ,sessionQ,eventQ,membershipQ]);if(be||me||se||ee||mse)return json(req,{error:"Unable to load attendance"},500);const recorderIds=[...new Set((events??[]).map(x=>x.recorded_by).filter(Boolean))] as string[],{data:recorders}=recorderIds.length?await admin.from("profiles").select("id,full_name").in("id",recorderIds):{data:[]};return json(req,{branches:branches??[],members:members??[],sessions:sessions??[],events:events??[],memberships:memberships??[],recorders:recorders??[],access:{role:access.role,branch_id:access.branch_id}})}
 if(req.method==="POST"){const body=await req.json();
  if(body.guest===true){
   const branchId=txt(body.branch_id,50),national=txt(body.national_id,20),name=txt(body.full_name,120),phone=txt(body.phone,30)||null,amount=Number(body.amount),method=txt(body.method,20),sessionId=txt(body.session_id,50)||null;
   if(!branchId||!/^\d{8,12}$/.test(national)||!Number.isSafeInteger(amount)||amount<=0||!["cash","pos","bank_transfer"].includes(method))return json(req,{error:"Invalid guest data"},400);
   if(scope&&branchId!==scope)return json(req,{error:"Branch access denied"},403);
   if(sessionId){const {data:s}=await admin.from("pool_sessions").select("id").eq("id",sessionId).eq("organization_id",org).eq("branch_id",branchId).maybeSingle();if(!s)return json(req,{error:"Session not found"},400)}
   let {data:member}=await admin.from("members").select("id,full_name,status").eq("organization_id",org).eq("national_id",national).maybeSingle();
   if(!member){
    const guestName=name.length>=2?name:("مهمان "+national.slice(-4));
    const {data:created,error:cerr}=await admin.from("members").insert({organization_id:org,home_branch_id:branchId,full_name:guestName,national_id:national,phone,status:"active",notes:"ثبت‌شده از میز پذیرش (مهمان)",created_by:auth.user.id}).select("id,full_name,status").single();
    if(cerr?.code==="23505"){const {data:existing}=await admin.from("members").select("id,full_name,status").eq("organization_id",org).eq("national_id",national).maybeSingle();member=existing}
    else if(cerr||!created)return json(req,{error:"Unable to create guest"},500);
    else member=created;
   }
   if(!member)return json(req,{error:"Unable to create guest"},500);
   if(member.status!=="active")return json(req,{error:"Member is blocked"},400);
   const {data:lastEvent}=await admin.from("attendance_events").select("id,event_type").eq("organization_id",org).eq("branch_id",branchId).eq("member_id",member.id).order("occurred_at",{ascending:false}).limit(1).maybeSingle();
   if(lastEvent?.event_type==="entry")return json(req,{error:"Member is already inside"},400);
   const {data:pay,error:perr}=await admin.from("payment_records").insert({organization_id:org,branch_id:branchId,member_id:member.id,amount,currency:"IRR",method,status:"paid",received_by:auth.user.id}).select("id").single();
   if(perr)return json(req,{error:"Unable to register payment"},500);
   const {data:ev,error:eerr}=await admin.from("attendance_events").insert({organization_id:org,branch_id:branchId,member_id:member.id,session_id:sessionId,event_type:"entry",method:"manual",recorded_by:auth.user.id}).select("id").single();
   if(eerr)return json(req,{error:"Unable to register entry"},500);
   await admin.from("audit_logs").insert({organization_id:org,actor_user_id:auth.user.id,action:"guest.entry",entity_type:"members",entity_id:member.id,details:{amount,method}});
   return json(req,{ok:true,member_id:member.id,member_name:member.full_name,payment_id:pay.id,event_id:ev.id},201);
  }
  const branchId=txt(body.branch_id,50),memberId=txt(body.member_id,50),eventType=txt(body.event_type,10),sessionId=txt(body.session_id,50)||null;if(!branchId||!memberId||!["entry","exit"].includes(eventType))return json(req,{error:"Invalid attendance data"},400);if(scope&&branchId!==scope)return json(req,{error:"Branch access denied"},403);const {data,error}=await admin.rpc("record_member_attendance",{p_organization_id:org,p_branch_id:branchId,p_member_id:memberId,p_session_id:sessionId,p_event_type:eventType,p_recorded_by:auth.user.id});if(error)return json(req,{error:error.message},400);return json(req,{ok:true,id:data},201)}
 return json(req,{error:"Method not allowed"},405);
});
