import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import {createClient} from "npm:@supabase/supabase-js@2.95.0";
const origins=new Set(["https://dolphin-abi-pool.gerayeli60.chatgpt.site","http://localhost:3000","http://localhost:3001"]),roles=new Set(["owner","branch_manager","receptionist"]);
function cors(req:Request){const o=req.headers.get("origin")??"";return{"Access-Control-Allow-Origin":origins.has(o)?o:"https://dolphin-abi-pool.gerayeli60.chatgpt.site","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, PATCH, OPTIONS","Content-Type":"application/json","Cache-Control":"no-store","Vary":"Origin"}}
function json(req:Request,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors(req)})}function txt(v:unknown,n:number){return String(v??"").trim().slice(0,n)}function iso(v:unknown){const d=new Date(String(v??""));return Number.isNaN(d.getTime())?null:d.toISOString()}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});const origin=req.headers.get("origin")??"";if(origin&&!origins.has(origin))return json(req,{error:"Forbidden"},403);
 const admin=createClient(Deno.env.get("SUPABASE_URL")??"",Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"",{auth:{persistSession:false,autoRefreshToken:false}}),token=req.headers.get("authorization")?.replace(/^Bearer\s+/i,"")??"";const {data:auth,error:authError}=await admin.auth.getUser(token);if(authError||!auth.user)return json(req,{error:"Unauthorized"},401);
 const {data:access}=await admin.from("organization_users").select("organization_id,role,branch_id,status").eq("user_id",auth.user.id).eq("status","active").maybeSingle();if(!access||!roles.has(access.role))return json(req,{error:"Staff access required"},403);const org=access.organization_id,scope=access.role==="owner"?null:access.branch_id;if(access.role!=="owner"&&!scope)return json(req,{error:"Branch access required"},403);
 if(req.method==="GET"){let sessionsQ=admin.from("pool_sessions").select("id,branch_id,title,starts_at,ends_at,capacity,audience,status,created_at").eq("organization_id",org).order("starts_at",{ascending:true}).limit(500),reservationsQ=admin.from("session_reservations").select("id,session_id,member_id,status,reserved_at,cancelled_at").eq("organization_id",org).order("reserved_at",{ascending:false}).limit(1000),membersQ=admin.from("members").select("id,member_number,full_name,home_branch_id,status").eq("organization_id",org).eq("status","active").order("full_name").limit(500),branchesQ=admin.from("branches").select("id,name,status").eq("organization_id",org).eq("status","active").order("name");if(scope){sessionsQ=sessionsQ.eq("branch_id",scope);membersQ=membersQ.eq("home_branch_id",scope);branchesQ=branchesQ.eq("id",scope)}
  const [{data:sessions,error:se},{data:reservations,error:re},{data:members,error:me},{data:branches,error:be}]=await Promise.all([sessionsQ,reservationsQ,membersQ,branchesQ]);if(se||re||me||be)return json(req,{error:"Unable to load sessions"},500);const sessionIds=new Set((sessions??[]).map(x=>x.id));return json(req,{sessions:sessions??[],reservations:(reservations??[]).filter(x=>sessionIds.has(x.session_id)),members:members??[],branches:branches??[],access:{role:access.role,branch_id:access.branch_id}})}
 const body=await req.json();
 if(req.method==="POST"&&body.type==="session"){if(!["owner","branch_manager"].includes(access.role))return json(req,{error:"Manager access required"},403);const title=txt(body.title,120),branchId=txt(body.branch_id,50),starts=iso(body.starts_at),ends=iso(body.ends_at),capacity=Number(body.capacity),audience=txt(body.audience,20);if(title.length<2||!branchId||!starts||!ends||new Date(ends)<=new Date(starts)||!Number.isInteger(capacity)||capacity<1||capacity>10000||!["all","women","men","children"].includes(audience))return json(req,{error:"Invalid session data"},400);if(scope&&branchId!==scope)return json(req,{error:"Branch access denied"},403);const {data:branch}=await admin.from("branches").select("id").eq("id",branchId).eq("organization_id",org).eq("status","active").maybeSingle();if(!branch)return json(req,{error:"Invalid branch"},400);const {data,error}=await admin.from("pool_sessions").insert({organization_id:org,branch_id:branchId,title,starts_at:starts,ends_at:ends,capacity,audience,status:"scheduled",created_by:auth.user.id}).select("id").single();if(error)return json(req,{error:"Unable to create session"},500);return json(req,{ok:true,id:data.id},201)}
 if(req.method==="POST"&&body.type==="reservation"){const sessionId=txt(body.session_id,50),memberId=txt(body.member_id,50);if(!sessionId||!memberId)return json(req,{error:"Invalid reservation data"},400);let sessionQ=admin.from("pool_sessions").select("id,branch_id").eq("id",sessionId).eq("organization_id",org);if(scope)sessionQ=sessionQ.eq("branch_id",scope);const {data:session}=await sessionQ.maybeSingle();if(!session)return json(req,{error:"Session not found"},404);const {data,error}=await admin.rpc("reserve_pool_session",{p_organization_id:org,p_session_id:sessionId,p_member_id:memberId,p_reserved_by:auth.user.id});if(error)return json(req,{error:error.message},error.code==="23505"?409:400);return json(req,{ok:true,id:data},201)}
 if(req.method==="PATCH"&&body.type==="reservation"&&body.action==="cancel"){const id=txt(body.reservation_id,50),{data:r}=await admin.from("session_reservations").select("id,session_id").eq("id",id).eq("organization_id",org).eq("status","confirmed").maybeSingle();if(!r)return json(req,{error:"Reservation not found"},404);if(scope){const {data:s}=await admin.from("pool_sessions").select("id").eq("id",r.session_id).eq("branch_id",scope).maybeSingle();if(!s)return json(req,{error:"Reservation not found"},404)}const {error}=await admin.rpc("cancel_pool_reservation",{p_organization_id:org,p_reservation_id:id,p_cancelled_by:auth.user.id});if(error)return json(req,{error:error.message},400);return json(req,{ok:true})}
 if(req.method==="PATCH"&&body.type==="session"){if(!["owner","branch_manager"].includes(access.role))return json(req,{error:"Manager access required"},403);const id=txt(body.session_id,50),status=txt(body.status,20);if(!["scheduled","cancelled","completed"].includes(status))return json(req,{error:"Invalid session status"},400);let q=admin.from("pool_sessions").update({status,updated_at:new Date().toISOString()}).eq("id",id).eq("organization_id",org);if(scope)q=q.eq("branch_id",scope);const {error}=await q;if(error)return json(req,{error:"Unable to update session"},500);return json(req,{ok:true})}
 return json(req,{error:"Method not allowed"},405);
});
