"use client";
import {ArrowRight,BarChart3,CalendarClock,Check,CircleDollarSign,Clock3,Download,Loader2,RefreshCw,ShieldCheck,Ticket,TrendingUp,Undo2,Users,Waves,X} from "lucide-react";
import {useCallback,useEffect,useState} from "react";
import {functionsUrl,supabase} from "../../lib/supabase-browser";
import "../members/members.css";
type Reports={range:{days:number;today:string},revenue:{today:number;todayCount:number;last7:number;range:number;rangeCount:number;daily:{day:string;amount:number;count:number}[]},methods:Record<string,{amount:number;count:number}>,voided:{count:number;amount:number;recent:{id:string;amount:number;reason:string|null;paid_at:string;voided_at:string|null;member:string}[]},members:{total:number;active:number;withActiveMembership:number;expiringSoon:{member_name:string;phone:string|null;plan_name:string|null;ends_on:string;remaining_sessions:number|null}[];expiredCount:number},sessions:{id:string;title:string;starts_at:string;capacity:number;status:string;booked:number}[]};
const money=(n:number)=>Number(n).toLocaleString("fa-IR"),date=(x:string)=>new Intl.DateTimeFormat("fa-IR").format(new Date(x)),dateTime=(x:string)=>new Intl.DateTimeFormat("fa-IR",{dateStyle:"short",timeStyle:"short"}).format(new Date(x)),dayName=(iso:string)=>["یکشنبه","دوشنبه","سه‌شنبه","چهارشنبه","پنج‌شنبه","جمعه","شنبه"][new Date(iso+"T00:00:00Z").getUTCDay()];
const methodLabels:Record<string,string>={cash:"نقدی",pos:"کارت‌خوان",bank_transfer:"انتقال بانکی"};
async function api(url:string="",init?:RequestInit){const {data}=await supabase.auth.getSession();const response=await fetch(functionsUrl+"/reports"+url,{...init,headers:{Authorization:`Bearer ${data.session?.access_token??""}`}});const result=await response.json();if(!response.ok)throw new Error(result.error??"خطا در دریافت گزارش‌ها");return result}
function downloadCsv(name:string,rows:(string|number)[][]){const csv="\uFEFF"+rows.map(r=>r.map(c=>`"${String(c??"").replace(/"/g,'""')}"`).join(",")).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}

export default function ReportsPage(){
 const [r,setR]=useState<Reports|null>(null),[loading,setLoading]=useState(true),[days,setDays]=useState(30),[toast,setToast]=useState("");
 const load=useCallback(async(d=days)=>{setLoading(true);try{setR(await api(`?days=${d}`))}catch(e){setToast(e instanceof Error?e.message:"خطا")}finally{setLoading(false)}},[days]);
 useEffect(()=>{void load()},[]); 
 const maxDaily=Math.max(...(r?.revenue.daily.map(d=>d.amount)??[1]),1);
 const methodRows=Object.entries(r?.methods??{});
 return <main className="users-page reports-page" dir="rtl"><header className="users-topbar"><a href="/" className="users-back"><ArrowRight/> بازگشت به داشبورد</a><div className="users-brand"><span><Waves/></span><b>دلفین آبی</b></div><div className="users-secure"><ShieldCheck/> گزارش عملکرد</div></header>
 <section className="users-container"><div className="users-heading"><div><small>تحلیل داده</small><h1>گزارش‌های مجموعه</h1><p>درآمد، عضویت‌ها و پُری سانس‌ها را ببینید و خروجی CSV بگیرید.</p></div><div style={{display:"flex",gap:9,alignItems:"center"}}><select value={days} onChange={e=>{const d=Number(e.target.value);setDays(d);void load(d)}} className="tenants-refresh" style={{width:"auto",height:42,padding:"0 12px"}}><option value={7}>۷ روز</option><option value={30}>۳۰ روز</option><option value={90}>۹۰ روز</option><option value={180}>۱۸۰ روز</option></select><button onClick={()=>void load()} className="tenants-refresh"><RefreshCw className={loading?"spin":""}/></button></div></div>
 {loading&&!r?<div className="users-empty"><Loader2 className="spin"/><p>در حال محاسبه گزارش‌ها...</p></div>:!r?<div className="users-empty"><BarChart3/><p>گزارشی در دسترس نیست.</p></div>:
 <>
 <section className="users-summary"><div><span className="violet"><CircleDollarSign/></span><p>درآمد امروز<b>{money(r.revenue.today)}</b><small style={{fontSize:10,color:"#8b8495"}}>{money(r.revenue.todayCount)} پرداخت</small></p></div><div><span className="green"><TrendingUp/></span><p>درآمد ۷ روز<b>{money(r.revenue.last7)}</b></p></div><div><span className="orange"><CircleDollarSign/></span><p>درآمد {money(r.range.days)} روز<b>{money(r.revenue.range)}</b></p></div><div><span className="violet"><Undo2/></span><p>ابطال‌ها<b>{money(r.voided.count)}</b><small style={{fontSize:10,color:"#8b8495"}}>{money(r.voided.amount)} ریال</small></p></div></section>
 <section className="detail-grid">
  <article className="detail-card wide"><div className="card-flex"><h2>روند درآمد ({money(r.range.days)} روز)</h2><button className="csv-button" onClick={()=>downloadCsv(`revenue-${r.range.days}d.csv`,[["تاریخ","درآمد (ریال)","تعداد پرداخت"],...r.revenue.daily.map(d=>[d.day,d.amount,d.count])])}><Download/> CSV</button></div><div className="report-bars">{r.revenue.daily.map(d=><div key={d.day} className="report-barcol" title={`${d.day}: ${d.amount} ریال`}><i style={{height:Math.max(3,Math.round(d.amount/maxDaily*100))+"%"}}/><small>{d.amount>0?dayName(d.day):""}</small></div>)}</div></article>
  <article className="detail-card"><h2>روش‌های پرداخت</h2>{methodRows.length===0?<p className="detail-empty">پرداختی در این بازه ثبت نشده است.</p>:<table className="detail-table"><thead><tr><th>روش</th><th>مبلغ</th><th>تعداد</th></tr></thead><tbody>{methodRows.map(([m,v])=><tr key={m}><td>{methodLabels[m]??m}</td><td><b>{money(v.amount)}</b> ریال</td><td>{money(v.count)}</td></tr>)}</tbody></table>}</article>
  <article className="detail-card"><h2>وضعیت اعضا</h2><div className="member-stat-grid"><div><b>{money(r.members.total)}</b><small>کل اعضا</small></div><div><b>{money(r.members.active)}</b><small>فعال</small></div><div><b>{money(r.members.withActiveMembership)}</b><small>اشتراک معتبر</small></div><div><b>{money(r.members.expiredCount)}</b><small>اشتراک منقضی</small></div></div>
   <div className="card-flex" style={{marginTop:14}}><h2>نزدیک انقضا (۷ روز)</h2><button className="csv-button" onClick={()=>downloadCsv("expiring-members.csv",[["نام","تلفن","طرح","تاریخ انقضا","جلسه باقی‌مانده"],...r.members.expiringSoon.map(x=>[x.member_name,x.phone??"",x.plan_name??"",x.ends_on,x.remaining_sessions??"نامحدود"])])}><Download/> CSV</button></div>
   {r.members.expiringSoon.length===0?<p className="detail-empty">عضوی در آستانه انقضا نیست.</p>:<table className="detail-table"><thead><tr><th>عضو</th><th>طرح</th><th>انقضا</th><th>تماس</th></tr></thead><tbody>{r.members.expiringSoon.map(x=><tr key={x.member_name+x.ends_on}><td><b>{x.member_name}</b></td><td>{x.plan_name??"—"}</td><td><span className="event-tag exit">{date(x.ends_on)}</span></td><td><small>{x.phone??"—"}</small></td></tr>)}</tbody></table>}</article>
  <article className="detail-card wide"><h2>پُری سانس‌های هفته اخیر</h2>{r.sessions.length===0?<p className="detail-empty">سانسی در این بازه ثبت نشده است.</p>:<table className="detail-table"><thead><tr><th>سانس</th><th>زمان</th><th>پُری</th><th>وضعیت</th></tr></thead><tbody>{r.sessions.map(s=><tr key={s.id}><td>{s.title}</td><td><small>{dateTime(s.starts_at)}</small></td><td><div className="occupancy-cell"><i><b style={{width:Math.min(100,Math.round(s.booked/s.capacity*100))+"%"}}/></i><small>{money(s.booked)} / {money(s.capacity)}</small></div></td><td>{s.status==="completed"?"برگزار شد":s.status==="cancelled"?"لغو":s.status==="scheduled"?"در برنامه":"—"}</td></tr>)}</tbody></table>}</article>
  <article className="detail-card wide"><h2>ابطال‌های اخیر</h2>{r.voided.recent.length===0?<p className="detail-empty">ابطالی در این بازه ثبت نشده است.</p>:<table className="detail-table"><thead><tr><th>عضو</th><th>مبلغ</th><th>دلیل</th><th>زمان پرداخت</th><th>زمان ابطال</th></tr></thead><tbody>{r.voided.recent.map(v=><tr key={v.id}><td>{v.member}</td><td><b>{money(v.amount)}</b> ریال</td><td>{v.reason??"—"}</td><td><small>{dateTime(v.paid_at)}</small></td><td><small>{v.voided_at?dateTime(v.voided_at):"—"}</small></td></tr>)}</tbody></table>}</article>
 </section>
 </>}
 </section>
 {toast&&<div className="users-toast"><Check/>{toast}<button onClick={()=>setToast("")}><X/></button></div>}</main>
}
