"use client";
import {ArrowRight,Banknote,Ban,Check,CircleDollarSign,CreditCard,Landmark,Loader2,RefreshCw,ShieldCheck,WalletCards,Waves,X} from "lucide-react";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {functionsUrl,supabase} from "../../lib/supabase-browser";
import "./payments.css";
type Membership={id:string;branch_id:string;member_id:string;plan_id:string;starts_on:string;ends_on:string;status:string};
type Payment={id:string;branch_id:string;member_id:string;membership_id:string;amount:number;method:string;status:string;reference_number:string|null;received_by:string;paid_at:string;void_reason:string|null};
type Member={id:string;member_number:number;full_name:string};type Plan={id:string;name:string;price_amount:number};type Branch={id:string;name:string};type Receiver={id:string;full_name:string};
const labels:Record<string,string>={cash:"نقدی",pos:"کارت‌خوان",bank_transfer:"انتقال بانکی",paid:"پرداخت‌شده",voided:"باطل‌شده"};
const errors:Record<string,string>={"Payment reference required":"شماره پیگیری برای این روش پرداخت الزامی است.","Pending membership not found":"اشتراک در انتظار پرداخت پیدا نشد.","Manager access required":"فقط مدیر می‌تواند پرداخت را باطل کند.","Void reason required":"دلیل ابطال را حداقل در سه حرف وارد کنید.","Membership is not pending":"این اشتراک دیگر در انتظار پرداخت نیست."};
async function api(init?:RequestInit){const {data}=await supabase.auth.getSession();const response=await fetch(functionsUrl+"/admin-payments",{...init,headers:{Authorization:`Bearer ${data.session?.access_token??""}`,"Content-Type":"application/json",...(init?.headers??{})}});const result=await response.json();if(!response.ok)throw new Error(errors[result.error]??result.error??"خطا در ارتباط با سرور");return result}
const money=(value:number)=>new Intl.NumberFormat("fa-IR").format(value),dateTime=(value:string)=>new Intl.DateTimeFormat("fa-IR",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
export default function PaymentsPage(){
 const [memberships,setMemberships]=useState<Membership[]>([]),[payments,setPayments]=useState<Payment[]>([]),[members,setMembers]=useState<Member[]>([]),[plans,setPlans]=useState<Plan[]>([]),[branches,setBranches]=useState<Branch[]>([]),[receivers,setReceivers]=useState<Receiver[]>([]),[role,setRole]=useState(""),[loading,setLoading]=useState(true),[modal,setModal]=useState<Membership|null>(null),[voiding,setVoiding]=useState<Payment|null>(null),[toast,setToast]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const r=await api();setMemberships(r.memberships);setPayments(r.payments);setMembers(r.members);setPlans(r.plans);setBranches(r.branches);setReceivers(r.receivers);setRole(r.access.role)}catch(e){setToast(e instanceof Error?e.message:"خطا در دریافت پرداخت‌ها")}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
 const memberMap=useMemo(()=>new Map(members.map(x=>[x.id,x])),[members]),planMap=useMemo(()=>new Map(plans.map(x=>[x.id,x])),[plans]),branchMap=useMemo(()=>new Map(branches.map(x=>[x.id,x])),[branches]),receiverMap=useMemo(()=>new Map(receivers.map(x=>[x.id,x])),[receivers]);
 const paidTotal=payments.filter(x=>x.status==="paid").reduce((sum,x)=>sum+x.amount,0),today=new Date().toDateString(),todayCount=payments.filter(x=>x.status==="paid"&&new Date(x.paid_at).toDateString()===today).length;
 return <main className="payments-page" dir="rtl"><header className="payments-top"><a href="/"><ArrowRight/> بازگشت به داشبورد</a><div><span><Waves/></span><b>دلفین آبی</b></div><small><ShieldCheck/> ثبت امن پرداخت دستی</small></header><section className="payments-container">
  <div className="payments-title"><div><small>صندوق و دریافت‌ها</small><h1>پرداخت‌های عضویت</h1><p>پرداخت نقدی، کارت‌خوان یا انتقال بانکی را ثبت کنید؛ عضویت همان لحظه فعال می‌شود.</p></div><button onClick={()=>void load()}><RefreshCw className={loading?"spin":""}/> بروزرسانی</button></div>
  <section className="payment-stats"><article><span><CircleDollarSign/></span><div><small>جمع پرداخت‌های معتبر</small><b>{money(paidTotal)} <em>ریال</em></b></div></article><article><span><WalletCards/></span><div><small>پرداخت‌های امروز</small><b>{todayCount.toLocaleString("fa-IR")}</b></div></article><article><span><CreditCard/></span><div><small>در انتظار پرداخت</small><b>{memberships.length.toLocaleString("fa-IR")}</b></div></article></section>
  <section className="payment-panel"><div className="panel-head"><div><h2>اشتراک‌های در انتظار پرداخت</h2><p>مبلغ هر اشتراک از تعرفه ثبت‌شده خوانده می‌شود و قابل تغییر دستی نیست.</p></div></div>{loading?<Empty loading/>:memberships.length===0?<Empty text="اشتراک در انتظار پرداختی وجود ندارد."/>:<div className="pending-grid">{memberships.map(item=>{const member=memberMap.get(item.member_id),plan=planMap.get(item.plan_id);return <article key={item.id}><div><span>{member?.full_name?.slice(0,1)??"ع"}</span><div><b>{member?.full_name??"عضو"}</b><small>شماره عضویت {member?.member_number?.toLocaleString("fa-IR")}</small></div></div><dl><div><dt>بسته</dt><dd>{plan?.name??"—"}</dd></div><div><dt>شعبه</dt><dd>{branchMap.get(item.branch_id)?.name??"—"}</dd></div></dl><strong>{money(plan?.price_amount??0)} <small>ریال</small></strong><button onClick={()=>setModal(item)}><Banknote/> ثبت پرداخت و فعال‌سازی</button></article>})}</div>}</section>
  <section className="payment-panel"><div className="panel-head"><div><h2>سوابق پرداخت</h2><p>تمام دریافت‌های دستی و موارد ابطال‌شده قابل پیگیری‌اند.</p></div></div>{loading?<Empty loading/>:payments.length===0?<Empty text="هنوز پرداختی ثبت نشده است."/>:<div className="payment-table-wrap"><table><thead><tr><th>عضو</th><th>مبلغ</th><th>روش</th><th>پیگیری</th><th>دریافت‌کننده</th><th>زمان</th><th>وضعیت</th><th></th></tr></thead><tbody>{payments.map(item=><tr key={item.id}><td><b>{memberMap.get(item.member_id)?.full_name??"عضو"}</b><small>{branchMap.get(item.branch_id)?.name}</small></td><td>{money(item.amount)} ریال</td><td>{labels[item.method]}</td><td>{item.reference_number??"—"}</td><td>{receiverMap.get(item.received_by)?.full_name??"کاربر"}</td><td>{dateTime(item.paid_at)}</td><td><span className={`pay-status ${item.status}`}>{labels[item.status]??item.status}</span>{item.void_reason&&<small>{item.void_reason}</small>}</td><td>{item.status==="paid"&&["owner","branch_manager"].includes(role)&&<button className="void-button" onClick={()=>setVoiding(item)}><Ban/> ابطال</button>}</td></tr>)}</tbody></table></div>}</section>
 </section>{modal&&<PayModal membership={modal} member={memberMap.get(modal.member_id)} plan={planMap.get(modal.plan_id)} onClose={()=>setModal(null)} onSaved={async()=>{setModal(null);setToast("پرداخت ثبت و عضویت فعال شد.");await load()}}/>}{voiding&&<VoidModal payment={voiding} onClose={()=>setVoiding(null)} onSaved={async()=>{setVoiding(null);setToast("پرداخت باطل و عضویت به حالت انتظار بازگشت.");await load()}}/>}{toast&&<div className="payment-toast"><Check/>{toast}<button onClick={()=>setToast("")}><X/></button></div>}</main>
}
function Empty({loading,text}:{loading?:boolean;text?:string}){return <div className="payment-empty">{loading?<Loader2 className="spin"/>:<WalletCards/>}<p>{text}</p></div>}
function PayModal({membership,member,plan,onClose,onSaved}:{membership:Membership;member?:Member;plan?:Plan;onClose:()=>void;onSaved:()=>void}){const [method,setMethod]=useState("cash"),[saving,setSaving]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);try{await api({method:"POST",body:JSON.stringify({membership_id:membership.id,method,reference_number:f.get("reference_number")})});onSaved()}catch(err){setError(err instanceof Error?err.message:"ثبت پرداخت ناموفق بود")}finally{setSaving(false)}}return <div className="payment-modal-backdrop"><form className="payment-modal" onSubmit={submit}><header><div><span><Banknote/></span><div><h2>ثبت پرداخت عضویت</h2><p>{member?.full_name} · {plan?.name}</p></div></div><button type="button" onClick={onClose}><X/></button></header><div className="locked-amount"><small>مبلغ قابل دریافت</small><b>{money(plan?.price_amount??0)} ریال</b></div><label>روش پرداخت<select value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">نقدی</option><option value="pos">کارت‌خوان</option><option value="bank_transfer">انتقال بانکی</option></select></label><label>شماره پیگیری {method==="cash"&&<small>(اختیاری)</small>}<input name="reference_number" required={method!=="cash"} maxLength={100} placeholder={method==="cash"?"در صورت وجود":"شماره مرجع تراکنش"}/></label>{error&&<p className="payment-error">{error}</p>}<footer><button type="button" onClick={onClose}>انصراف</button><button className="confirm" disabled={saving}>{saving?<Loader2 className="spin"/>:<Check/>} ثبت و فعال‌سازی</button></footer></form></div>}
function VoidModal({payment,onClose,onSaved}:{payment:Payment;onClose:()=>void;onSaved:()=>void}){const [saving,setSaving]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);try{await api({method:"PATCH",body:JSON.stringify({payment_id:payment.id,void_reason:f.get("void_reason")})});onSaved()}catch(err){setError(err instanceof Error?err.message:"ابطال پرداخت ناموفق بود")}finally{setSaving(false)}}return <div className="payment-modal-backdrop"><form className="payment-modal" onSubmit={submit}><header><div><span className="danger"><Ban/></span><div><h2>ابطال پرداخت</h2><p>مبلغ {money(payment.amount)} ریال باطل می‌شود.</p></div></div><button type="button" onClick={onClose}><X/></button></header><p className="void-note">با ابطال، عضویت دوباره به وضعیت «در انتظار پرداخت» برمی‌گردد.</p><label>دلیل ابطال<textarea name="void_reason" required minLength={3} maxLength={300}/></label>{error&&<p className="payment-error">{error}</p>}<footer><button type="button" onClick={onClose}>انصراف</button><button className="confirm danger-button" disabled={saving}>{saving?<Loader2 className="spin"/>:<Ban/>} تایید ابطال</button></footer></form></div>}
