-- Dolphin Abi — approved MVP schema draft
-- PostgreSQL 17 / Supabase. This is a reviewable schema, not yet a migration.

create extension if not exists citext with schema extensions;

-- Allow PostgREST to resolve extension-backed column types such as citext.
alter role authenticator set pgrst.db_extra_search_path = 'extensions';
create extension if not exists pgcrypto;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 120),
  slug extensions.citext not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  status text not null default 'active' check (status in ('active','suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.branches (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 120),
  code extensions.citext not null,
  phone text,
  address text,
  capacity integer not null default 0 check (capacity >= 0),
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, code),
  unique (id, organization_id)
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username extensions.citext not null unique check (username ~ '^[a-z0-9][a-z0-9._-]{2,31}$'),
  full_name text not null check (char_length(full_name) between 2 and 120),
  phone text,
  must_change_password boolean not null default true,
  account_status text not null default 'active' check (account_status in ('active','blocked')),
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.organization_users (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null check (role in ('owner','branch_manager','receptionist','member')),
  branch_id uuid,
  status text not null default 'active' check (status in ('active','inactive')),
  created_at timestamptz not null default now(),
  primary key (organization_id, user_id),
  foreign key (branch_id, organization_id)
    references public.branches(id, organization_id) on delete restrict,
  constraint staff_branch_required check (
    role in ('owner','member') or branch_id is not null
  )
);

create table public.members (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  home_branch_id uuid not null,
  auth_user_id uuid references public.profiles(id) on delete set null,
  member_number bigint generated by default as identity,
  full_name text not null check (char_length(full_name) between 2 and 120),
  phone text,
  national_id text,
  birth_date date,
  emergency_phone text,
  status text not null default 'active' check (status in ('active','inactive','blocked')),
  notes text,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, member_number),
  unique (organization_id, national_id),
  unique (id, organization_id),
  foreign key (home_branch_id, organization_id)
    references public.branches(id, organization_id) on delete restrict
);

create table public.membership_plans (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  duration_days integer not null check (duration_days > 0),
  session_limit integer check (session_limit is null or session_limit > 0),
  price_amount bigint not null check (price_amount >= 0),
  currency text not null default 'IRR' check (currency = 'IRR'),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, name),
  unique (id, organization_id)
);

create table public.memberships (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid not null,
  member_id uuid not null,
  plan_id uuid not null,
  starts_on date not null,
  ends_on date not null,
  remaining_sessions integer check (remaining_sessions is null or remaining_sessions >= 0),
  status text not null default 'active' check (status in ('pending','active','expired','cancelled')),
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_on >= starts_on),
  unique (id, organization_id),
  foreign key (branch_id, organization_id)
    references public.branches(id, organization_id) on delete restrict,
  foreign key (member_id, organization_id)
    references public.members(id, organization_id) on delete restrict,
  foreign key (plan_id, organization_id)
    references public.membership_plans(id, organization_id) on delete restrict
);

create table public.payment_records (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid not null,
  member_id uuid,
  membership_id uuid,
  amount bigint not null check (amount > 0),
  currency text not null default 'IRR' check (currency = 'IRR'),
  method text not null check (method in ('cash','pos','bank_transfer')),
  status text not null default 'paid' check (status in ('paid','voided','refunded')),
  reference_number text,
  received_by uuid not null references public.profiles(id) on delete restrict,
  paid_at timestamptz not null default now(),
  voided_at timestamptz,
  voided_by uuid references public.profiles(id) on delete restrict,
  void_reason text,
  created_at timestamptz not null default now(),
  check ((status = 'voided') = (voided_at is not null)),
  foreign key (branch_id, organization_id)
    references public.branches(id, organization_id) on delete restrict,
  foreign key (member_id, organization_id)
    references public.members(id, organization_id) on delete restrict,
  foreign key (membership_id, organization_id)
    references public.memberships(id, organization_id) on delete restrict
);

create table public.pool_sessions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid not null,
  title text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  capacity integer not null check (capacity > 0),
  audience text not null default 'all' check (audience in ('all','women','men','children')),
  status text not null default 'scheduled' check (status in ('scheduled','cancelled','completed')),
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at),
  unique (id, organization_id),
  foreign key (branch_id, organization_id)
    references public.branches(id, organization_id) on delete cascade
);

create table public.session_reservations (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  session_id uuid not null,
  member_id uuid not null,
  status text not null default 'confirmed' check (status in ('confirmed','cancelled','attended','no_show')),
  reserved_by uuid not null references public.profiles(id) on delete restrict,
  reserved_at timestamptz not null default now(),
  cancelled_at timestamptz,
  unique (session_id, member_id),
  foreign key (session_id, organization_id)
    references public.pool_sessions(id, organization_id) on delete cascade,
  foreign key (member_id, organization_id)
    references public.members(id, organization_id) on delete cascade
);

create table public.attendance_events (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  branch_id uuid not null,
  member_id uuid not null,
  session_id uuid,
  event_type text not null check (event_type in ('entry','exit')),
  method text not null default 'manual' check (method in ('manual','rfid','qr')),
  recorded_by uuid references public.profiles(id) on delete restrict,
  occurred_at timestamptz not null default now(),
  foreign key (branch_id, organization_id)
    references public.branches(id, organization_id) on delete restrict,
  foreign key (member_id, organization_id)
    references public.members(id, organization_id) on delete restrict,
  foreign key (session_id, organization_id)
    references public.pool_sessions(id, organization_id) on delete set null (session_id)
);

create table public.audit_logs (
  id bigint generated always as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Foreign-key and common filter indexes.
create index branches_org_idx on public.branches (organization_id);
create index org_users_user_idx on public.organization_users (user_id, status);
create index org_users_branch_idx on public.organization_users (branch_id) where branch_id is not null;
create index members_org_branch_idx on public.members (organization_id, home_branch_id, status);
create index members_auth_user_idx on public.members (auth_user_id) where auth_user_id is not null;
create index members_phone_idx on public.members (organization_id, phone) where phone is not null;
create index memberships_member_status_idx on public.memberships (member_id, status, ends_on desc);
create index payments_org_paid_idx on public.payment_records (organization_id, paid_at desc);
create index payments_member_idx on public.payment_records (member_id, paid_at desc) where member_id is not null;
create index sessions_branch_start_idx on public.pool_sessions (branch_id, starts_at, status);
create index reservations_member_idx on public.session_reservations (member_id, reserved_at desc);
create index attendance_member_time_idx on public.attendance_events (member_id, occurred_at desc);
create index attendance_branch_time_idx on public.attendance_events (branch_id, occurred_at desc);
create index audit_org_time_idx on public.audit_logs (organization_id, created_at desc);
create index attendance_org_idx on public.attendance_events (organization_id);
create index attendance_branch_org_idx on public.attendance_events (branch_id, organization_id);
create index attendance_member_org_idx on public.attendance_events (member_id, organization_id);
create index attendance_session_org_idx on public.attendance_events (session_id, organization_id) where session_id is not null;
create index attendance_recorded_by_idx on public.attendance_events (recorded_by) where recorded_by is not null;
create index audit_actor_idx on public.audit_logs (actor_user_id) where actor_user_id is not null;
create index members_home_branch_org_idx on public.members (home_branch_id, organization_id);
create index members_created_by_idx on public.members (created_by);
create index memberships_org_idx on public.memberships (organization_id);
create index memberships_branch_org_idx on public.memberships (branch_id, organization_id);
create index memberships_member_org_idx on public.memberships (member_id, organization_id);
create index memberships_plan_org_idx on public.memberships (plan_id, organization_id);
create index memberships_created_by_idx on public.memberships (created_by);
create index org_users_branch_org_idx on public.organization_users (branch_id, organization_id) where branch_id is not null;
create index payments_branch_org_idx on public.payment_records (branch_id, organization_id);
create index payments_member_org_idx on public.payment_records (member_id, organization_id) where member_id is not null;
create index payments_membership_org_idx on public.payment_records (membership_id, organization_id) where membership_id is not null;
create index payments_received_by_idx on public.payment_records (received_by);
create index payments_voided_by_idx on public.payment_records (voided_by) where voided_by is not null;
create index sessions_org_idx on public.pool_sessions (organization_id);
create index sessions_branch_org_idx on public.pool_sessions (branch_id, organization_id);
create index sessions_created_by_idx on public.pool_sessions (created_by);
create index reservations_org_idx on public.session_reservations (organization_id);
create index reservations_session_org_idx on public.session_reservations (session_id, organization_id);
create index reservations_member_org_idx on public.session_reservations (member_id, organization_id);
create index reservations_reserved_by_idx on public.session_reservations (reserved_by);

-- Authorization helpers live outside the exposed API schema.
create or replace function private.has_org_role(target_org_id uuid, allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.organization_users ou
      join public.profiles p on p.id = ou.user_id
      where ou.organization_id = target_org_id
        and ou.user_id = (select auth.uid())
        and ou.status = 'active'
        and p.account_status = 'active'
        and ou.role = any(allowed_roles)
    );
$$;

revoke all on function private.has_org_role(uuid, text[]) from public, anon;
grant usage on schema private to authenticated;
grant execute on function private.has_org_role(uuid, text[]) to authenticated;

-- RLS is mandatory for every table reachable through the Data API.
alter table public.organizations enable row level security;
alter table public.branches enable row level security;
alter table public.profiles enable row level security;
alter table public.organization_users enable row level security;
alter table public.members enable row level security;
alter table public.membership_plans enable row level security;
alter table public.memberships enable row level security;
alter table public.payment_records enable row level security;
alter table public.pool_sessions enable row level security;
alter table public.session_reservations enable row level security;
alter table public.attendance_events enable row level security;
alter table public.audit_logs enable row level security;

create policy organizations_read on public.organizations for select to authenticated
using (private.has_org_role(id, array['owner','branch_manager','receptionist','member']));
create policy organizations_owner_update on public.organizations for update to authenticated
using (private.has_org_role(id, array['owner']))
with check (private.has_org_role(id, array['owner']));

create policy branches_read on public.branches for select to authenticated
using (private.has_org_role(organization_id, array['owner','branch_manager','receptionist','member']));
create policy branches_insert on public.branches for insert to authenticated
with check (private.has_org_role(organization_id, array['owner']));
create policy branches_update on public.branches for update to authenticated
using (private.has_org_role(organization_id, array['owner']))
with check (private.has_org_role(organization_id, array['owner']));
create policy branches_delete on public.branches for delete to authenticated
using (private.has_org_role(organization_id, array['owner']));

create policy profiles_self_read on public.profiles for select to authenticated
using (id = (select auth.uid()));
create policy profiles_self_update on public.profiles for update to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create policy org_users_read on public.organization_users for select to authenticated
using (user_id = (select auth.uid()) or private.has_org_role(organization_id, array['owner','branch_manager']));
create policy org_users_owner_insert on public.organization_users for insert to authenticated
with check (private.has_org_role(organization_id, array['owner']));
create policy org_users_owner_update on public.organization_users for update to authenticated
using (private.has_org_role(organization_id, array['owner']))
with check (private.has_org_role(organization_id, array['owner']));
create policy org_users_owner_delete on public.organization_users for delete to authenticated
using (private.has_org_role(organization_id, array['owner']));

create policy members_read on public.members for select to authenticated
using (
  auth_user_id = (select auth.uid())
  or private.has_org_role(organization_id, array['owner','branch_manager','receptionist'])
);
create policy members_staff_insert on public.members for insert to authenticated
with check (private.has_org_role(organization_id, array['owner','branch_manager','receptionist']));
create policy members_staff_update on public.members for update to authenticated
using (private.has_org_role(organization_id, array['owner','branch_manager','receptionist']))
with check (private.has_org_role(organization_id, array['owner','branch_manager','receptionist']));

create policy plans_read on public.membership_plans for select to authenticated
using (private.has_org_role(organization_id, array['owner','branch_manager','receptionist','member']));
create policy plans_insert on public.membership_plans for insert to authenticated
with check (private.has_org_role(organization_id, array['owner','branch_manager']));
create policy plans_update on public.membership_plans for update to authenticated
using (private.has_org_role(organization_id, array['owner','branch_manager']))
with check (private.has_org_role(organization_id, array['owner','branch_manager']));
create policy plans_delete on public.membership_plans for delete to authenticated
using (private.has_org_role(organization_id, array['owner','branch_manager']));

create policy memberships_read on public.memberships for select to authenticated
using (
  private.has_org_role(organization_id, array['owner','branch_manager','receptionist'])
  or exists (select 1 from public.members m where m.id = member_id and m.auth_user_id = (select auth.uid()))
);
create policy memberships_staff_insert on public.memberships for insert to authenticated
with check (private.has_org_role(organization_id, array['owner','branch_manager','receptionist']));
create policy memberships_staff_update on public.memberships for update to authenticated
using (private.has_org_role(organization_id, array['owner','branch_manager','receptionist']))
with check (private.has_org_role(organization_id, array['owner','branch_manager','receptionist']));

create policy payments_read on public.payment_records for select to authenticated
using (
  private.has_org_role(organization_id, array['owner','branch_manager','receptionist'])
  or exists (select 1 from public.members m where m.id = member_id and m.auth_user_id = (select auth.uid()))
);
create policy payments_staff_insert on public.payment_records for insert to authenticated
with check (private.has_org_role(organization_id, array['owner','branch_manager','receptionist']));
create policy payments_manager_update on public.payment_records for update to authenticated
using (private.has_org_role(organization_id, array['owner','branch_manager']))
with check (private.has_org_role(organization_id, array['owner','branch_manager']));

create policy sessions_read on public.pool_sessions for select to authenticated
using (private.has_org_role(organization_id, array['owner','branch_manager','receptionist','member']));
create policy sessions_insert on public.pool_sessions for insert to authenticated
with check (private.has_org_role(organization_id, array['owner','branch_manager']));
create policy sessions_update on public.pool_sessions for update to authenticated
using (private.has_org_role(organization_id, array['owner','branch_manager']))
with check (private.has_org_role(organization_id, array['owner','branch_manager']));
create policy sessions_delete on public.pool_sessions for delete to authenticated
using (private.has_org_role(organization_id, array['owner','branch_manager']));

create policy reservations_read on public.session_reservations for select to authenticated
using (
  private.has_org_role(organization_id, array['owner','branch_manager','receptionist'])
  or exists (select 1 from public.members m where m.id = member_id and m.auth_user_id = (select auth.uid()))
);
create policy reservations_insert on public.session_reservations for insert to authenticated
with check (
  private.has_org_role(organization_id, array['owner','branch_manager','receptionist'])
  or (reserved_by = (select auth.uid()) and exists (
    select 1 from public.members m where m.id = member_id and m.auth_user_id = (select auth.uid())
  ))
);
create policy reservations_update on public.session_reservations for update to authenticated
using (
  private.has_org_role(organization_id, array['owner','branch_manager','receptionist'])
  or exists (select 1 from public.members m where m.id = member_id and m.auth_user_id = (select auth.uid()))
)
with check (
  private.has_org_role(organization_id, array['owner','branch_manager','receptionist'])
  or exists (select 1 from public.members m where m.id = member_id and m.auth_user_id = (select auth.uid()))
);

create policy attendance_read on public.attendance_events for select to authenticated
using (
  private.has_org_role(organization_id, array['owner','branch_manager','receptionist'])
  or exists (select 1 from public.members m where m.id = member_id and m.auth_user_id = (select auth.uid()))
);
create policy attendance_staff_insert on public.attendance_events for insert to authenticated
with check (private.has_org_role(organization_id, array['owner','branch_manager','receptionist']));

create policy audit_manager_read on public.audit_logs for select to authenticated
using (private.has_org_role(organization_id, array['owner','branch_manager']));

-- Explicit Data API exposure; no anonymous table access in the MVP.
revoke all on all tables in schema public from anon;
grant select on public.profiles to authenticated;
grant update (full_name, phone) on public.profiles to authenticated;
grant select, update on public.organizations to authenticated;
grant select, insert, update, delete on public.branches to authenticated;
grant select, insert, update, delete on public.organization_users to authenticated;
grant select, insert, update on public.members to authenticated;
grant select, insert, update, delete on public.membership_plans to authenticated;
grant select, insert, update on public.memberships to authenticated;
grant select, insert, update on public.payment_records to authenticated;
grant select, insert, update, delete on public.pool_sessions to authenticated;
grant select, insert, update on public.session_reservations to authenticated;
grant select, insert on public.attendance_events to authenticated;
grant select on public.audit_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
