"use client";
import {ArrowRight,Ban,Building2,Check,Edit3,Loader2,Phone,Plus,RefreshCw,Search,ShieldCheck,UserCheck,UserRound,Users,Waves,X} from "lucide-react";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {functionsUrl,supabase} from "../../lib/supabase-browser";
type Branch={id:string;name:string;status:string};
type Membership={plan_name:string|null;status:string;ends_on:string;remaining_sessions:number|null};
type Member={id:string;home_branch_id:string;member_number:number;full_name:string;phone:string|null;national_id:string|null;birth_date:string|null;emergency_phone:string|null;status:"active"|"inactive"|"blocked";notes:string|null;created_at:string;membership:Membership|null};
const statusLabels={active:"فعال",inactive:"غیرفعال",blocked:"مسدود"};
const errors:Record<string,string>={"National ID already exists":"عضوی با این کد ملی قبلاً ثبت شده است.","Invalid national ID":"کد ملی باید فقط شامل ۸ تا ۱۲ رقم باشد.","Branch access denied":"شما به اعضای این شعبه دسترسی ندارید.","Staff access required":"دسترسی این بخش فقط برای کارکنان مجاز است."};
async function api(init?:RequestInit){const {data}=await supabase.auth.getSession();const response=await fetch(functionsUrl+"/admin-members",{...init,headers:{Authorization:`Bearer ${data.session?.access_token??""}`,"Content-Type":"application/json",...(init?.headers??{})}});const result=await response.json();if(!response.ok)throw new Error(errors[result.error]??result.error??"خطا در ارتباط با سرور");return result}

export default function MembersPage(){
 const [members,setMembers]=useState<Member[]>([]),[branches,setBranches]=useState<Branch[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[query,setQuery]=useState(""),[status,setStatus]=useState("all"),[branch,setBranch]=useState("all"),[editing,setEditing]=useState<Member|null|undefined>(undefined),[toast,setToast]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const r=await api();setMembers(r.members);setBranches(r.branches)}catch(e){setToast(e instanceof Error?e.message:"خطا در دریافت اعضا")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return members.filter(m=>(status==="all"||m.status===status)&&(branch==="all"||m.home_branch_id===branch)&&(!q||m.full_name.toLowerCase().includes(q)||m.phone?.includes(q)||m.national_id?.includes(q)||String(m.member_number).includes(q)))},[members,query,status,branch]);
 async function setMemberStatus(member:Member,next:string){setBusy(member.id);try{await api({method:"PATCH",body:JSON.stringify({member_id:member.id,action:"set_status",status:next})});setToast("وضعیت عضو بروزرسانی شد");await load()}catch(e){setToast(e instanceof Error?e.message:"عملیات ناموفق بود")}finally{setBusy("")}}
 return <main className="users-page members-page" dir="rtl"><header className="users-topbar"><a href="/" className="users-back"><ArrowRight/> بازگشت به داشبورد</a><div className="users-brand"><span><Waves/></span><b>دلفین آبی</b></div><div className="users-secure"><ShieldCheck/> پرونده امن اعضا</div></header>
 <section className="users-container"><div className="users-heading"><div><small>باشگاه مشتریان</small><h1>اعضای استخر</h1><p>اطلاعات هویتی، شعبه و وضعیت عضویت مراجعه‌کنندگان را مدیریت کنید.</p></div><button className="users-primary" onClick={()=>setEditing(null)}><Plus/> ثبت عضو جدید</button></div>
 <section className="users-summary"><div><span className="violet"><Users/></span><p>کل اعضا<b>{members.length}</b></p></div><div><span className="green"><UserCheck/></span><p>اعضای فعال<b>{members.filter(m=>m.status==="active").length}</b></p></div><div><span className="orange"><Building2/></span><p>دارای اشتراک فعال<b>{members.filter(m=>m.membership?.status==="active").length}</b></p></div></section>
 <section className="users-panel"><div className="member-tools"><label className="member-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام، تلفن، کد ملی یا شماره عضویت..."/></label><select value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">همه شعب</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">همه وضعیت‌ها</option><option value="active">فعال</option><option value="inactive">غیرفعال</option><option value="blocked">مسدود</option></select><button onClick={()=>void load()}><RefreshCw className={loading?"spin":""}/></button></div>
 {loading?<div className="users-empty"><Loader2 className="spin"/><p>در حال دریافت اعضا...</p></div>:filtered.length===0?<div className="users-empty"><UserRound/><p>عضوی پیدا نشد.</p></div>:<div className="users-table-wrap"><table className="users-table member-table"><thead><tr><th>عضو</th><th>شعبه</th><th>اشتراک فعلی</th><th>تماس</th><th>وضعیت</th><th>عملیات</th></tr></thead><tbody>{filtered.map(member=>{const home=branches.find(b=>b.id===member.home_branch_id);return <tr key={member.id}><td><div className="user-identity"><span>{member.full_name.slice(0,1)}</span><div><b>{member.full_name}</b><small>شماره عضویت: {member.member_number.toLocaleString("fa-IR")}</small></div></div></td><td><div className="user-access"><b>{home?.name??"—"}</b><small>{member.national_id?`کد ملی: ${member.national_id}`:"کد ملی ثبت نشده"}</small></div></td><td>{member.membership?<div className="membership-cell"><b>{member.membership.plan_name??"بسته عضویت"}</b><small>تا {new Intl.DateTimeFormat("fa-IR").format(new Date(member.membership.ends_on))}</small></div>:<span className="no-membership">بدون اشتراک</span>}</td><td><span className="member-phone"><Phone/>{member.phone??"ثبت نشده"}</span></td><td><span className={`status ${member.status==="active"?"active":"blocked"}`}>{statusLabels[member.status]}</span></td><td><div className="user-actions"><button title="ویرایش" onClick={()=>setEditing(member)}><Edit3/></button><button className={member.status==="active"?"danger":"success"} disabled={busy===member.id} title={member.status==="active"?"غیرفعال‌کردن":"فعال‌کردن"} onClick={()=>void setMemberStatus(member,member.status==="active"?"inactive":"active")}>{busy===member.id?<Loader2 className="spin"/>:member.status==="active"?<Ban/>:<Check/>}</button></div></td></tr>})}</tbody></table></div>}</section></section>
 {editing!==undefined&&<MemberModal member={editing} branches={branches} onClose={()=>setEditing(undefined)} onSaved={async number=>{setEditing(undefined);setToast(number?`عضو با شماره ${Number(number).toLocaleString("fa-IR")} ثبت شد`:"اطلاعات عضو ذخیره شد");await load()}}/>}{toast&&<div className="users-toast"><Check/>{toast}<button onClick={()=>setToast("")}><X/></button></div>}</main>
}
function MemberModal({member,branches,onClose,onSaved}:{member:Member|null;branches:Branch[];onClose:()=>void;onSaved:(number?:number)=>void}){
 const [saving,setSaving]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget),body={full_name:f.get("full_name"),home_branch_id:f.get("home_branch_id"),phone:f.get("phone"),national_id:f.get("national_id"),birth_date:f.get("birth_date"),emergency_phone:f.get("emergency_phone"),notes:f.get("notes")};try{const r=member?await api({method:"PATCH",body:JSON.stringify({member_id:member.id,action:"update",...body})}):await api({method:"POST",body:JSON.stringify(body)});onSaved(r.member_number)}catch(err){setError(err instanceof Error?err.message:"ذخیره عضو ناموفق بود")}finally{setSaving(false)}}
 return <div className="users-modal-backdrop"><form className="users-modal member-modal" onSubmit={submit}><div className="modal-head"><div><span><UserRound/></span><div><h2>{member?"ویرایش پرونده عضو":"ثبت عضو جدید"}</h2><p>اطلاعات پایه عضو را وارد کنید.</p></div></div><button type="button" onClick={onClose}><X/></button></div><div className="modal-grid"><label className="wide">نام و نام خانوادگی<input name="full_name" defaultValue={member?.full_name} required minLength={2} autoFocus/></label><label>شعبه<select name="home_branch_id" defaultValue={member?.home_branch_id??branches[0]?.id} required>{branches.filter(b=>b.status==="active").map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>شماره تلفن<input name="phone" defaultValue={member?.phone??""} dir="ltr" placeholder="0912..."/></label><label>کد ملی<input name="national_id" defaultValue={member?.national_id??""} dir="ltr" inputMode="numeric" pattern="[0-9]{8,12}"/></label><label>تاریخ تولد<input name="birth_date" defaultValue={member?.birth_date??""} type="date" dir="ltr"/></label><label>تلفن اضطراری<input name="emergency_phone" defaultValue={member?.emergency_phone??""} dir="ltr"/></label><label className="wide">یادداشت<textarea name="notes" defaultValue={member?.notes??""} rows={3} placeholder="حساسیت، نکات پزشکی یا توضیحات ضروری"/></label></div>{error&&<p className="modal-error">{error}</p>}<footer><button type="button" onClick={onClose}>انصراف</button><button className="users-primary" disabled={saving}>{saving?<Loader2 className="spin"/>:<Check/>} ذخیره عضو</button></footer></form></div>
}
