"use client";
import {ArrowRight,Ban,Building2,CalendarClock,Check,KeyRound,Loader2,Plus,RefreshCw,ShieldCheck,Users,Waves,X} from "lucide-react";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {functionsUrl,supabase} from "../../lib/supabase-browser";
import "../members/members.css";
type Tenant={id:string;name:string;slug:string;status:string;subscription_ends_on:string|null;created_at:string;branch_count:number;user_count:number;member_count:number;active_member_count:number;expired:boolean};
type TenantUser={user_id:string;role:string;username:string|null;full_name:string;account_status:string;must_change_password:boolean;last_login_at:string|null};
type Credential={username:string;temp_password:string;name:string}|null;
const money=(n:number)=>n.toLocaleString("fa-IR"),date=(x:string)=>new Intl.DateTimeFormat("fa-IR").format(new Date(x)),dateTime=(x:string)=>new Intl.DateTimeFormat("fa-IR",{dateStyle:"short",timeStyle:"short"}).format(new Date(x));
const roleLabels:Record<string,string>={owner:"مدیر کل",branch_manager:"مدیر شعبه",receptionist:"پذیرش",member:"عضو"};
async function api(url:string="",init?:RequestInit){const {data}=await supabase.auth.getSession();const response=await fetch(functionsUrl+"/platform-tenants"+url,{...init,headers:{Authorization:`Bearer ${data.session?.access_token??""}`,"Content-Type":"application/json"}});const result=await response.json();if(!response.ok)throw new Error(result.error??"خطا در ارتباط با سرور");return result}

export default function TenantsPage(){
 const [tenants,setTenants]=useState<Tenant[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[creating,setCreating]=useState(false),[credential,setCredential]=useState<Credential>(null),[detail,setDetail]=useState<{org:Tenant;users:TenantUser[]}|null>(null),[toast,setToast]=useState(""),[error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const r=await api();setTenants(r.organizations)}catch(e){setError(e instanceof Error?e.message:"خطا")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function patch(orgId:string,action:string,extra:Record<string,unknown>={},message=""){setBusy(orgId+action);try{await api("",{method:"PATCH",body:JSON.stringify({org_id:orgId,action,...extra})});setToast(message||"انجام شد");await load()}catch(e){setToast(e instanceof Error?e.message:"عملیات ناموفق بود")}finally{setBusy("")}}
 return <main className="users-page tenants-page" dir="rtl"><header className="users-topbar"><a href="/" className="users-back"><ArrowRight/> بازگشت به داشبورد</a><div className="users-brand"><span><Waves/></span><b>دلفین آبی</b></div><div className="users-secure"><ShieldCheck/> پنل مدیر پلتفرم</div></header>
 <section className="users-container"><div className="users-heading"><div><small>مدیریت SaaS</small><h1>مجموعه‌های مشتریان</h1><p>ساخت مجموعه جدید، فعال‌سازی دستی اشتراک و تعلیق حساب مشتریان از اینجا انجام می‌شود.</p></div><div style={{display:"flex",gap:9}}><button onClick={()=>void load()} className="tenants-refresh"><RefreshCw className={loading?"spin":""}/></button><button className="users-primary" onClick={()=>setCreating(true)}><Plus/> مجموعه جدید</button></div></div>
 {error&&<p className="modal-error">{error}</p>}
 {loading?<div className="users-empty"><Loader2 className="spin"/><p>در حال دریافت مجموعه‌ها...</p></div>:tenants.length===0?<div className="users-empty"><Building2/><p>هنوز مجموعه‌ای ثبت نشده است.</p></div>:
 <div className="tenants-grid">{tenants.map(t=>{const expired=t.expired,suspended=t.status!=="active";return <article key={t.id} className={`tenant-card ${suspended?"suspended":""}`}>
  <div className="tenant-head"><div><b>{t.name}</b><small>{t.slug}</small></div><span className={`status ${suspended?"blocked":expired?"blocked":"active"}`}>{suspended?"معلق":expired?"منقضی":"فعال"}</span></div>
  <div className="tenant-stats"><div><Users/><b>{money(t.member_count)}</b><small>عضو</small></div><div><Building2/><b>{money(t.branch_count)}</b><small>شعبه</small></div><div><ShieldCheck/><b>{money(t.user_count)}</b><small>کاربر</small></div></div>
  <div className={`tenant-sub ${expired&&!suspended?"warn":""}`}><CalendarClock/><span>{t.subscription_ends_on?`اشتراک تا ${date(t.subscription_ends_on)}`:"بدون محدودیت زمانی"}</span></div>
  <div className="tenant-actions">
   <button onClick={async()=>{try{const d=await api(`?org_id=${t.id}`);setDetail({org:t,users:d.users})}catch{setToast("دریافت جزئیات ناموفق بود")}}}>کاربران</button>
   <button className="extend" onClick={()=>{const d=new Date();d.setMonth(d.getMonth()+1);const iso=d.toISOString().slice(0,10);void patch(t.id,"set_subscription",{ends_on:iso},"اشتراک یک ماه تمدید شد")}} disabled={busy===t.id+"set_subscription"}><CalendarClock/> تمدید ۱ ماه</button>
   <button onClick={()=>{const d=new Date();d.setFullYear(d.getFullYear()+1);const iso=d.toISOString().slice(0,10);void patch(t.id,"set_subscription",{ends_on:iso},"اشتراک یک سال تمدید شد")}} disabled={busy===t.id+"set_subscription"}>تمدید ۱ سال</button>
   {suspended?<button className="activate" disabled={busy===t.id+"set_status"} onClick={()=>void patch(t.id,"set_status",{status:"active"},"مجموعه فعال شد")}><Check/> رفع تعلیق</button>:<button className="danger" disabled={busy===t.id+"set_status"} onClick={()=>void patch(t.id,"set_status",{status:"suspended"},"مجموعه معلق شد")}><Ban/> تعلیق</button>}
  </div>
 </article>})}</div>}
 </section>
 {creating&&<CreateModal onClose={()=>setCreating(false)} onDone={(c)=>{setCreating(false);setCredential(c);void load()}}/>}
 {credential&&<div className="users-modal-backdrop"><div className="users-modal credential-modal"><div className="credential-icon"><KeyRound/></div><h2>{credential.name?"رمز موقت ساخته شد":"مجموعه ساخته شد"}</h2><p>این مشخصات فقط همین یک‌بار نمایش داده می‌شوند. در جای امن ذخیره و به مشتری تحویل دهید. کاربر در اولین ورود باید رمز جدید تعیین کند.</p><div className="credential-box"><label>نام کاربری</label><b>{credential.username}</b><label>رمز موقت</label><code>{credential.temp_password}</code></div><button className="users-primary copy-credential" onClick={()=>{void navigator.clipboard.writeText(`نام کاربری: ${credential.username}\nرمز موقت: ${credential.temp_password}`);setToast("کپی شد")}}>کپی مشخصات</button><button className="credential-close" onClick={()=>setCredential(null)}>بستن</button></div></div>}
 {detail&&<div className="users-modal-backdrop"><div className="users-modal tenants-detail-modal"><div className="modal-head"><div><span><Users/></span><div><h2>{detail.org.name}</h2><p>کاربران مجموعه و مدیریت دسترسی‌ها</p></div></div><button onClick={()=>setDetail(null)}><X/></button></div><div className="tenants-users">{detail.users.map(u=><div key={u.user_id} className="tenant-user"><div><b>{u.full_name}</b><small>{u.username} · {roleLabels[u.role]??u.role}{u.must_change_password?" · در انتظار تغییر رمز":""}{u.last_login_at?` · آخرین ورود ${dateTime(u.last_login_at)}`:" · بدون ورود"}</small></div><button disabled={busy===u.user_id} onClick={async()=>{try{const r=await api("",{method:"PATCH",body:JSON.stringify({org_id:detail.org.id,action:"reset_user_password",user_id:u.user_id})});setCredential({username:u.username??"",temp_password:r.temp_password,name:u.full_name});setDetail(null)}catch(e){setToast(e instanceof Error?e.message:"عملیات ناموفق بود")}}}><KeyRound/> رمز جدید</button></div>)}</div></div></div>}
 {toast&&<div className="users-toast"><Check/>{toast}<button onClick={()=>setToast("")}><X/></button></div>}</main>
}
function CreateModal({onClose,onDone}:{onClose:()=>void;onDone:(c:{username:string;temp_password:string;name:string})=>void}){
 const [saving,setSaving]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);try{const r=await api("",{method:"POST",body:JSON.stringify({name:f.get("name"),branch_name:f.get("branch_name")||"شعبه مرکزی",owner_full_name:f.get("owner_full_name"),username:f.get("username"),ends_on:f.get("ends_on")||null})});onDone({username:r.username,temp_password:r.temp_password,name:String(f.get("owner_full_name"))})}catch(err){setError(err instanceof Error?err.message:"ساخت مجموعه ناموفق بود");setSaving(false)}}
 return <div className="users-modal-backdrop"><form className="users-modal member-modal" onSubmit={submit}><div className="modal-head"><div><span><Building2/></span><div><h2>مجموعه جدید</h2><p>سازمان، شعبه اول و حساب مدیر کل مجموعه ساخته می‌شود.</p></div></div><button type="button" onClick={onClose}><X/></button></div><div className="modal-grid"><label className="wide">نام مجموعه (استخر)<input name="name" required minLength={2} placeholder="مثلاً استخر موج طلایی" autoFocus/></label><label className="wide">نام مدیر کل مجموعه<input name="owner_full_name" required minLength={2}/></label><label className="wide">نام کاربری مدیر (انگلیسی)<input name="username" required dir="ltr" pattern="[a-zA-Z0-9][a-zA-Z0-9._-]{2,31}" placeholder="wave-manager"/></label><label>نام شعبه اول<input name="branch_name" defaultValue="شعبه مرکزی"/></label><label>اعتبار اشتراک<input name="ends_on" type="date" dir="ltr"/><small style={{color:"#8b8495",fontSize:10}}>خالی = بدون محدودیت</small></label></div>{error&&<p className="modal-error">{error}</p>}<footer><button type="button" onClick={onClose}>انصراف</button><button className="users-primary" disabled={saving}>{saving?<Loader2 className="spin"/>:<Plus/>} ساخت مجموعه</button></footer></form></div>
}
