"use client";
import {ArrowRight,Ban,CalendarDays,Check,Clock3,Edit3,Layers3,Loader2,Plus,RefreshCw,ShieldCheck,Ticket,Users,Waves,X} from "lucide-react";
import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {functionsUrl,supabase} from "../../lib/supabase-browser";
type Plan={id:string;name:string;duration_days:number;session_limit:number|null;price_amount:number;currency:string;is_active:boolean};
type Member={id:string;member_number:number;full_name:string;home_branch_id:string;status:string};
type Branch={id:string;name:string;status:string};
type Membership={id:string;branch_id:string;member_id:string;plan_id:string;starts_on:string;ends_on:string;remaining_sessions:number|null;status:string;created_at:string};
const errors:Record<string,string>={"Plan name already exists":"بسته‌ای با این نام قبلاً ثبت شده است.","Member already has an overlapping membership":"این عضو در بازه انتخاب‌شده اشتراک فعال یا در انتظار دارد.","Owner access required":"فقط مدیر کل می‌تواند بسته‌های عضویت را تغییر دهد."};
async function api(init?:RequestInit){const {data}=await supabase.auth.getSession();const response=await fetch(functionsUrl+"/admin-memberships",{...init,headers:{Authorization:`Bearer ${data.session?.access_token??""}`,"Content-Type":"application/json",...(init?.headers??{})}});const result=await response.json();if(!response.ok)throw new Error(errors[result.error]??result.error??"خطا در ارتباط با سرور");return result}
const money=(value:number)=>new Intl.NumberFormat("fa-IR").format(value);
export default function MembershipsPage(){
 const [plans,setPlans]=useState<Plan[]>([]),[members,setMembers]=useState<Member[]>([]),[branches,setBranches]=useState<Branch[]>([]),[memberships,setMemberships]=useState<Membership[]>([]),[role,setRole]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[planModal,setPlanModal]=useState<Plan|null|undefined>(undefined),[issue,setIssue]=useState(false),[toast,setToast]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const r=await api();setPlans(r.plans);setMembers(r.members);setBranches(r.branches);setMemberships(r.memberships);setRole(r.access.role)}catch(e){setToast(e instanceof Error?e.message:"خطا در دریافت اشتراک‌ها")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 const memberMap=useMemo(()=>new Map(members.map(m=>[m.id,m])),[members]),planMap=useMemo(()=>new Map(plans.map(p=>[p.id,p])),[plans]),branchMap=useMemo(()=>new Map(branches.map(b=>[b.id,b])),[branches]);
 async function patch(id:string,payload:object){setBusy(id);try{await api({method:"PATCH",body:JSON.stringify(payload)});setToast("تغییرات ذخیره شد");await load()}catch(e){setToast(e instanceof Error?e.message:"عملیات ناموفق بود")}finally{setBusy("")}}
 return <main className="users-page memberships-page" dir="rtl"><header className="users-topbar"><a href="/" className="users-back"><ArrowRight/> بازگشت به داشبورد</a><div className="users-brand"><span><Waves/></span><b>دلفین آبی</b></div><div className="users-secure"><ShieldCheck/> اشتراک بدون پرداخت آنلاین</div></header><section className="users-container">
 <div className="users-heading"><div><small>عضویت و تعرفه‌ها</small><h1>بسته‌ها و اشتراک‌ها</h1><p>بسته‌های قابل فروش را تعریف و برای اعضا اشتراک در انتظار پرداخت صادر کنید.</p></div><div className="membership-head-actions">{role==="owner"&&<button onClick={()=>setPlanModal(null)}><Plus/> بسته جدید</button>}<button className="users-primary" onClick={()=>setIssue(true)}><Ticket/> صدور اشتراک</button></div></div>
 <div className="plan-grid">{plans.map(plan=><article className={plan.is_active?"plan-card":"plan-card disabled"} key={plan.id}><div><span><Layers3/></span><em>{plan.is_active?"فعال":"غیرفعال"}</em></div><h2>{plan.name}</h2><strong>{money(plan.price_amount)} <small>ریال</small></strong><ul><li><CalendarDays/>{plan.duration_days.toLocaleString("fa-IR")} روز اعتبار</li><li><Clock3/>{plan.session_limit===null?"جلسات نامحدود":`${plan.session_limit.toLocaleString("fa-IR")} جلسه`}</li></ul>{role==="owner"&&<footer><button onClick={()=>setPlanModal(plan)}><Edit3/> ویرایش</button><button disabled={busy===plan.id} onClick={()=>void patch(plan.id,{type:"plan",action:"set_status",plan_id:plan.id,is_active:!plan.is_active})}>{busy===plan.id?<Loader2 className="spin"/>:plan.is_active?<Ban/>:<Check/>}{plan.is_active?"غیرفعال":"فعال"}</button></footer>}</article>)}</div>
 <section className="users-panel membership-list"><div className="membership-list-head"><div><h2>اشتراک‌های صادرشده</h2><p>اشتراک‌های جدید تا ثبت پرداخت در وضعیت «در انتظار» می‌مانند.</p></div><button onClick={()=>void load()}><RefreshCw className={loading?"spin":""}/></button></div>{loading?<div className="users-empty"><Loader2 className="spin"/></div>:memberships.length===0?<div className="users-empty"><Ticket/><p>هنوز اشتراکی صادر نشده است.</p></div>:<div className="users-table-wrap"><table className="users-table"><thead><tr><th>عضو</th><th>بسته</th><th>شعبه</th><th>بازه اعتبار</th><th>جلسات</th><th>وضعیت</th><th></th></tr></thead><tbody>{memberships.map(item=>{const member=memberMap.get(item.member_id),plan=planMap.get(item.plan_id);return <tr key={item.id}><td><b>{member?.full_name??"عضو"}</b><small className="table-sub">#{member?.member_number?.toLocaleString("fa-IR")}</small></td><td>{plan?.name??"—"}</td><td>{branchMap.get(item.branch_id)?.name??"—"}</td><td><span className="date-range">{new Intl.DateTimeFormat("fa-IR").format(new Date(item.starts_on))}<i/> {new Intl.DateTimeFormat("fa-IR").format(new Date(item.ends_on))}</span></td><td>{item.remaining_sessions===null?"نامحدود":item.remaining_sessions.toLocaleString("fa-IR")}</td><td><span className={`membership-status ${item.status}`}>{item.status==="pending"?"در انتظار پرداخت":item.status==="active"?"فعال":item.status==="cancelled"?"لغوشده":"منقضی"}</span></td><td><button className="cancel-membership" disabled={busy===item.id||!["pending","active"].includes(item.status)} onClick={()=>void patch(item.id,{type:"membership",action:"cancel",membership_id:item.id})}>لغو</button></td></tr>})}</tbody></table></div>}</section></section>
 {planModal!==undefined&&<PlanModal plan={planModal} onClose={()=>setPlanModal(undefined)} onSaved={async()=>{setPlanModal(undefined);setToast("بسته ذخیره شد");await load()}}/>}{issue&&<IssueModal members={members} plans={plans.filter(p=>p.is_active)} branches={branches} onClose={()=>setIssue(false)} onSaved={async()=>{setIssue(false);setToast("اشتراک در انتظار پرداخت صادر شد");await load()}}/>}{toast&&<div className="users-toast"><Check/>{toast}<button onClick={()=>setToast("")}><X/></button></div>}</main>
}
function PlanModal({plan,onClose,onSaved}:{plan:Plan|null;onClose:()=>void;onSaved:()=>void}){const [saving,setSaving]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget),body={type:"plan",name:f.get("name"),duration_days:Number(f.get("duration_days")),session_limit:f.get("session_limit"),price_amount:Number(f.get("price_amount"))};try{await api({method:plan?"PATCH":"POST",body:JSON.stringify(plan?{...body,plan_id:plan.id}:body)});onSaved()}catch(err){setError(err instanceof Error?err.message:"ذخیره بسته ناموفق بود")}finally{setSaving(false)}}return <div className="users-modal-backdrop"><form className="users-modal" onSubmit={submit}><div className="modal-head"><div><span><Layers3/></span><div><h2>{plan?"ویرایش بسته":"بسته عضویت جدید"}</h2><p>قیمت به ریال ثبت می‌شود.</p></div></div><button type="button" onClick={onClose}><X/></button></div><div className="modal-grid"><label className="wide">نام بسته<input name="name" defaultValue={plan?.name} required minLength={2}/></label><label>مدت اعتبار (روز)<input name="duration_days" type="number" min={1} max={3650} defaultValue={plan?.duration_days??30} required/></label><label>تعداد جلسات<input name="session_limit" type="number" min={1} placeholder="خالی = نامحدود" defaultValue={plan?.session_limit??""}/></label><label className="wide">قیمت (ریال)<input name="price_amount" type="number" min={0} step={1000} defaultValue={plan?.price_amount??0} required/></label></div>{error&&<p className="modal-error">{error}</p>}<footer><button type="button" onClick={onClose}>انصراف</button><button className="users-primary" disabled={saving}>{saving?<Loader2 className="spin"/>:<Check/>} ذخیره</button></footer></form></div>}
function IssueModal({members,plans,branches,onClose,onSaved}:{members:Member[];plans:Plan[];branches:Branch[];onClose:()=>void;onSaved:()=>void}){const [saving,setSaving]=useState(false),[error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const f=new FormData(e.currentTarget);try{await api({method:"POST",body:JSON.stringify({type:"membership",member_id:f.get("member_id"),plan_id:f.get("plan_id"),branch_id:f.get("branch_id"),starts_on:f.get("starts_on")})});onSaved()}catch(err){setError(err instanceof Error?err.message:"صدور اشتراک ناموفق بود")}finally{setSaving(false)}}return <div className="users-modal-backdrop"><form className="users-modal" onSubmit={submit}><div className="modal-head"><div><span><Ticket/></span><div><h2>صدور اشتراک</h2><p>پرداخت در مرحله بعد ثبت می‌شود.</p></div></div><button type="button" onClick={onClose}><X/></button></div><div className="modal-grid"><label className="wide">عضو<select name="member_id" required><option value="">انتخاب عضو</option>{members.map(m=><option key={m.id} value={m.id}>{m.full_name} — #{m.member_number}</option>)}</select></label><label>بسته<select name="plan_id" required><option value="">انتخاب بسته</option>{plans.map(p=><option key={p.id} value={p.id}>{p.name} — {money(p.price_amount)} ریال</option>)}</select></label><label>شعبه<select name="branch_id" required><option value="">انتخاب شعبه</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="wide">تاریخ شروع<input name="starts_on" type="date" defaultValue={new Date().toISOString().slice(0,10)} required dir="ltr"/></label></div>{error&&<p className="modal-error">{error}</p>}<footer><button type="button" onClick={onClose}>انصراف</button><button className="users-primary" disabled={saving}>{saving?<Loader2 className="spin"/>:<Ticket/>} صدور در انتظار پرداخت</button></footer></form></div>}
