"use client";
import {ArrowRight,Ban,CalendarDays,Check,Clock3,Edit3,Loader2,Phone,Receipt,ShieldCheck,Ticket,UserRound,Waves,X} from "lucide-react";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {useParams} from "next/navigation";
import {functionsUrl,supabase} from "../../../lib/supabase-browser";
import "../members.css";
type Member={id:string;home_branch_id:string;member_number:number;full_name:string;phone:string|null;national_id:string|null;birth_date:string|null;emergency_phone:string|null;status:"active"|"inactive"|"blocked";notes:string|null;created_at:string;updated_at:string};
type Branch={id:string;name:string;status:string};
type Membership={id:string;plan_id:string;plan_name:string|null;status:string;starts_on:string;ends_on:string;remaining_sessions:number|null;created_at:string};
type Payment={id:string;branch_id:string;membership_id:string|null;amount:number;method:string;status:string;reference_number:string|null;received_by:string;paid_at:string;voided_at:string|null;void_reason:string|null;receiver_name:string|null};
type Reservation={id:string;session_id:string;status:string;reserved_at:string;cancelled_at:string|null;session:{id:string;title:string;starts_at:string;ends_at:string}|null};
type Attendance={id:string;branch_id:string;session_id:string|null;event_type:string;occurred_at:string;session:{id:string;title:string}|null};
const statusLabels:Record<string,string>={active:"فعال",inactive:"غیرفعال",blocked:"مسدود",pending:"در انتظار پرداخت",expired:"منقضی",cancelled:"لغوشده",confirmed:"تأییدشده",attended:"حاضر شد",no_show:"عدم حضور"};
const methodLabels:Record<string,string>={cash:"نقدی",pos:"کارت‌خوان",bank_transfer:"انتقال بانکی"};
const money=(n:number)=>n.toLocaleString("fa-IR"),date=(x:string)=>new Intl.DateTimeFormat("fa-IR").format(new Date(x)),dateTime=(x:string)=>new Intl.DateTimeFormat("fa-IR",{dateStyle:"short",timeStyle:"short"}).format(new Date(x)),time=(x:string)=>new Intl.DateTimeFormat("fa-IR",{timeStyle:"short"}).format(new Date(x));
const errors:Record<string,string>={"National ID already exists":"عضوی با این کد ملی قبلاً ثبت شده است.","Invalid national ID":"کد ملی باید فقط شامل ۸ تا ۱۲ رقم باشد.","Branch access denied":"شما به این عضو دسترسی ندارید.","Member not found":"عضو پیدا نشد."};
async function api(url:string,init?:RequestInit){const {data}=await supabase.auth.getSession();const response=await fetch(functionsUrl+url,{...init,headers:{Authorization:`Bearer ${data.session?.access_token??""}`,"Content-Type":"application/json"}});const result=await response.json();if(!response.ok)throw new Error(errors[result.error]??result.error??"خطا در ارتباط با سرور");return result}

export default function MemberDetailPage(){
 const {id}=useParams<{id:string}>();
 const [member,setMember]=useState<Member|null>(null),[branches,setBranches]=useState<Branch[]>([]),[memberships,setMemberships]=useState<Membership[]>([]),[payments,setPayments]=useState<Payment[]>([]),[reservations,setReservations]=useState<Reservation[]>([]),[attendance,setAttendance]=useState<Attendance[]>([]),[createdBy,setCreatedBy]=useState<string|null>(null),[role,setRole]=useState("");
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[editing,setEditing]=useState(false),[toast,setToast]=useState("");
 const load=useCallback(async()=>{setLoading(true);try{const r=await api(`/admin-members?id=${id}`);setMember(r.member);setBranches(r.branches);setMemberships(r.memberships);setPayments(r.payments);setReservations(r.reservations);setAttendance(r.attendance);setCreatedBy(r.created_by_name);setRole(r.access.role)}catch(e){setToast(e instanceof Error?e.message:"خطا در دریافت پرونده عضو")}finally{setLoading(false)}},[id]);
 useEffect(()=>{void load()},[load]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy("save");const f=new FormData(e.currentTarget);try{await api("/admin-members",{method:"PATCH",body:JSON.stringify({member_id:id,action:"update",full_name:f.get("full_name"),home_branch_id:f.get("home_branch_id"),phone:f.get("phone"),national_id:f.get("national_id"),birth_date:f.get("birth_date"),emergency_phone:f.get("emergency_phone"),notes:f.get("notes")})});setEditing(false);setToast("اطلاعات عضو ذخیره شد");await load()}catch(err){setToast(err instanceof Error?err.message:"ذخیره ناموفق بود")}finally{setBusy("")}}
 async function toggleStatus(){setBusy("status");try{await api("/admin-members",{method:"PATCH",body:JSON.stringify({member_id:id,action:"set_status",status:member?.status==="active"?"inactive":"active"})});setToast("وضعیت عضو بروزرسانی شد");await load()}catch(err){setToast(err instanceof Error?err.message:"عملیات ناموفق بود")}finally{setBusy("")}}
 const activeMembership=memberships.find(x=>x.status==="active");
 return <main className="users-page member-detail" dir="rtl"><header className="users-topbar"><a href="/members" className="users-back"><ArrowRight/> بازگشت به اعضا</a><div className="users-brand"><span><Waves/></span><b>دلفین آبی</b></div><div className="users-secure"><ShieldCheck/> پرونده عضو</div></header>
 <section className="users-container">{loading?<div className="users-empty"><Loader2 className="spin"/><p>در حال دریافت پرونده...</p></div>:!member?<div className="users-empty"><UserRound/><p>عضو پیدا نشد.</p></div>:
 <>
 <div className="detail-hero"><div className="detail-id"><span>{member.full_name.slice(0,1)}</span><div><h1>{member.full_name}</h1><p>شماره عضویت {money(member.member_number)} · {branches.find(b=>b.id===member.home_branch_id)?.name??"—"}</p><div className="detail-chips"><em className={`status ${member.status==="active"?"active":"blocked"}`}>{statusLabels[member.status]}</em>{activeMembership&&<em className="chip green"><Ticket/>{activeMembership.plan_name} تا {date(activeMembership.ends_on)}</em>}{member.phone&&<em className="chip"><Phone/>{member.phone}</em>}</div></div></div><div className="detail-actions"><button onClick={()=>void load()}><Clock3 className={loading?"spin":""}/></button><button className="users-primary" onClick={()=>setEditing(true)}><Edit3/> ویرایش پرونده</button><button className="ghost-danger" disabled={busy==="status"} onClick={()=>void toggleStatus()}>{member.status==="active"?<><Ban/> غیرفعال‌کردن</>:<><Check/> فعال‌کردن</>}</button></div></div>
 <section className="detail-grid">
  <article className="detail-card"><h2>اطلاعات هویتی</h2><dl><div><dt>کد ملی</dt><dd>{member.national_id??"ثبت نشده"}</dd></div><div><dt>تاریخ تولد</dt><dd>{member.birth_date?date(member.birth_date):"—"}</dd></div><div><dt>تلفن</dt><dd>{member.phone??"—"}</dd></div><div><dt>تلفن اضطراری</dt><dd>{member.emergency_phone??"—"}</dd></div><div><dt>تاریخ ثبت</dt><dd>{dateTime(member.created_at)}</dd></div><div><dt>ثبت‌کننده</dt><dd>{createdBy??"—"}</dd></div></dl>{member.notes&&<p className="detail-notes"><b>یادداشت:</b> {member.notes}</p>}</article>
  <article className="detail-card"><h2>اشتراک‌ها ({money(memberships.length)})</h2>{memberships.length===0?<p className="detail-empty">هنوز اشتراکی صادر نشده است.</p>:<table className="detail-table"><thead><tr><th>طرح</th><th>بازه</th><th>جلسه</th><th>وضعیت</th></tr></thead><tbody>{memberships.map(x=><tr key={x.id}><td>{x.plan_name??"—"}</td><td><small>{date(x.starts_on)} تا {date(x.ends_on)}</small></td><td>{x.remaining_sessions===null?"نامحدود":x.remaining_sessions===0?"تمام‌شده":money(x.remaining_sessions)}</td><td><span className={`status ${x.status==="active"?"active":x.status==="pending"?"blocked":"inactive"}`}>{statusLabels[x.status]??x.status}</span></td></tr>)}</tbody></table>}</article>
  <article className="detail-card"><h2>پرداخت‌ها ({money(payments.length)})</h2>{payments.length===0?<p className="detail-empty">پرداختی ثبت نشده است.</p>:<table className="detail-table"><thead><tr><th>مبلغ</th><th>روش</th><th>زمان</th><th>وضعیت</th><th></th></tr></thead><tbody>{payments.map(x=><tr key={x.id}><td><b>{money(x.amount)}</b> ریال</td><td>{methodLabels[x.method]}</td><td><small>{dateTime(x.paid_at)}</small></td><td><span className={`status ${x.status==="paid"?"active":"blocked"}`}>{x.status==="paid"?"پرداخت‌شده":"باطل‌شده"}</span>{x.void_reason&&<small className="void-reason">{x.void_reason}</small>}</td><td>{x.status==="paid"&&<a className="receipt-link" href={`/receipt/${x.id}`} target="_blank"><Receipt/> رسید</a>}</td></tr>)}</tbody></table>}</article>
  <article className="detail-card"><h2>رزرو سانس‌ها ({money(reservations.length)})</h2>{reservations.length===0?<p className="detail-empty">رزروی ثبت نشده است.</p>:<table className="detail-table"><thead><tr><th>سانس</th><th>زمان</th><th>وضعیت</th></tr></thead><tbody>{reservations.slice(0,20).map(x=><tr key={x.id}><td>{x.session?.title??"—"}</td><td><small>{x.session?dateTime(x.session.starts_at):"—"}</small></td><td><span className={`status ${x.status==="confirmed"?"active":x.status==="attended"?"active":"inactive"}`}>{statusLabels[x.status]??x.status}</span></td></tr>)}</tbody></table>}</article>
  <article className="detail-card wide"><h2>ورود و خروج ({money(attendance.length)})</h2>{attendance.length===0?<p className="detail-empty">ترددی ثبت نشده است.</p>:<table className="detail-table"><thead><tr><th>نوع</th><th>سانس</th><th>زمان</th></tr></thead><tbody>{attendance.slice(0,30).map(x=><tr key={x.id}><td><span className={`event-tag ${x.event_type}`}>{x.event_type==="entry"?"ورود":"خروج"}</span></td><td>{x.session?.title??"ورود آزاد"}</td><td><small>{dateTime(x.occurred_at)}</small></td></tr>)}</tbody></table>}</article>
 </section>
 </>}
 </section>
 {editing&&member&&<div className="users-modal-backdrop"><form className="users-modal member-modal" onSubmit={save}><div className="modal-head"><div><span><UserRound/></span><div><h2>ویرایش پرونده عضو</h2><p>اطلاعات پایه عضو را ویرایش کنید.</p></div></div><button type="button" onClick={()=>setEditing(false)}><X/></button></div><div className="modal-grid"><label className="wide">نام و نام خانوادگی<input name="full_name" defaultValue={member.full_name} required minLength={2}/></label><label>شعبه<select name="home_branch_id" defaultValue={member.home_branch_id} required>{branches.filter(b=>b.status==="active").map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>شماره تلفن<input name="phone" defaultValue={member.phone??""} dir="ltr" placeholder="0912..."/></label><label>کد ملی<input name="national_id" defaultValue={member.national_id??""} dir="ltr" inputMode="numeric" pattern="[0-9]{8,12}"/></label><label>تاریخ تولد<input name="birth_date" defaultValue={member.birth_date??""} type="date" dir="ltr"/></label><label>تلفن اضطراری<input name="emergency_phone" defaultValue={member.emergency_phone??""} dir="ltr"/></label><label className="wide">یادداشت<textarea name="notes" defaultValue={member.notes??""} rows={3}/></label></div><footer><button type="button" onClick={()=>setEditing(false)}>انصراف</button><button className="users-primary" disabled={busy==="save"}>{busy==="save"?<Loader2 className="spin"/>:<Check/>} ذخیره</button></footer></form></div>}
 {toast&&<div className="users-toast"><Check/>{toast}<button onClick={()=>setToast("")}><X/></button></div>}</main>
}
